livechat/design-system

- package.json
- src/components/Dropdown/Dropdown.js
- src/components/Dropdown/DropdownList.js
- src/components/Dropdown/DropdownList.test.js
- src/components/Dropdown/DropdownListItem.js
- src/components/Dropdown/__snapshots__/DropdownList.test.js.snap
- src/components/Switch/Switch.js
- src/components/Switch/__snapshots__/Switch.test.js.snap
- src/interfaces/dropdowns.d.ts
We noticed the issue in Dropdown component. When the number of dropdown list items changes or items are removed on click (screen) Dropdown is not updating its position. Dynamic content of dropdown could also trigger this bug.
We decided to listen on Dropdown content wrapper resize to properly handle those cases. 
References:
- similar issue solution in the other library: https://github.com/palantir/blueprint/pull/2718
- ResizeObserver polyfill: https://github.com/que-etc/resize-observer-polyfill
- popper issue (closed): https://github.com/FezVrasta/popper.js/issues/85 
Also I added props for custom keycodes setup and autofocus first item on creating component and list items count change (filtering)
> Handling Dropdown content resize

- package.json
- src/components/Dropdown/DropdownList.js
- src/components/Dropdown/__snapshots__/DropdownList.test.js.snap
- src/interfaces/dropdowns.d.ts
Building list with sublist using DropdownList component can be a bit problematic. @sgraczyk encountered one more issue when building canned responses dropdown - while hiding one of 2 lists its events are still attached and using keyboard arrows change a focused item in 2 lists.
> Adding new property to control dropdown keyboard events

- package.json
- src/components/Dropdown/DropdownList.js
- src/components/Dropdown/DropdownListItem.js
- src/interfaces/dropdowns.d.ts
- we should always pass `event` as argument of event handlers in component API 
- in this case, the event helps with recognizing of keyboard or mouse usage (we need to add different amplitude event in AA for keyboard and mouse)
> Passing event as argument of `onItemSelect` property

- CHANGELOG.md
- package.json
_Release: 2019-06-19_
- adding optional `onOpen` property to `PopperTooltip` - for tooltips with `click` and `hover` trigger action types
- extending `Dropdown` and `DropdownList` components:
- adding dropdown content resize observer
- custom key codes for Dropdown close and DropdownList select events
- prevent default on item select with the keydown event
- adding autofocus first item to DropdownList component
- adding a new property to control dropdown keyboard events
- passing event as argument of `onItemSelect` property (optional)
- refactoring Dropdown and Switch prop types and default props - it was not visible in the docs
- `Toast` component styles fix - elements inside of `Toast` were positioned incorectly (ie11, firefox, safari)
---
> Release 0.4.2

- src/components/Toast/style.scss
> Added no wrap to toast action

- src/components/InAppMessage/style.scss
> Changing spacing for mobile InApp footer

- src/interfaces/switch.d.ts
https://github.com/livechat/design-system/pull/136/files#diff-480884be778ca4f56fa81be6ae696310R3 - This change caused an error in AA because global Omit type was introduced in Typescript 3.5 (AA is on ts 3.1.6)
> Adding Omit type to support AA typescript version

- CHANGELOG.md
- package.json
- src/interfaces/switch.d.ts
_Release: 2019-10-09_
- Adding `Omit` type to support typescript in version 3.1 (#138)
---
> Release 0.5.4

- packages/design-system/src/components/Dropdown/DropdownList.js
- packages/design-system/src/interfaces/dropdowns.d.ts
Focus can’t be controlled at the moment, but in some cases, it could be helpful - Jakub Sikora, from the Developer Platform team, needs to automatically focus the current version of docs on dropdown open.
Take a look at the comment:
https://livechatinc.atlassian.net/browse/DPS-1258?focusedCommentId=63598&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-63598
Done in PR:
- fixing keydown and hover handlers - items hover handlers were disabled after keyboard keys use when there was no list scroll
- allow autofocusedItemId prop
> [AA-7213] Allow autofocusedItemId prop

- packages/design-system/src/components/InputField/style.scss
- packages/design-system/src/components/NumericInputField/__snapshots__/NumericInput.test.js.snap
- packages/design-system/src/components/NumericInputField/style.scss
- packages/design-system/src/components/TextAreaField/style.scss
It appears that the native behavior of Safari related to the `-webkit-appearance` has caused the inner shadows to be displayed inside of the `InputField`, `NumericInputField` and `TextAreaField `:
Using `-webkit-appearance: none;` might be an overkill, but after digging a bit it seems that `background-clip: padding-box;` does the trick.
I have also updated the snapshots for the NumericInput, as they seemed not to be up-to-date.
> Fix inner-shadow appearing on Safari mobile

- packages/design-system/src/components/ButtonGroup/style.scss
I used `ButtonGroup` in the agent app and saw that the `box-shadow` styles were placed in a different order. `.lc-btn:focus` was placed after `.lc-btn-group .lc-btn` which made the `box-shadow` of the regular button more important than disabled `box-shadow: none` for the grouped buttons. I wanted the styles of the group to be more specific.
> AA-7719 ButtonGroup > Disable box-shadow for :focus and :active states

- packages/design-system/CHANGELOG.md
- packages/design-system/package-lock.json
- packages/design-system/package.json
- packages/design-system/src/components/InputField/style.scss
- packages/design-system/src/components/MultiSelectField/MultiSelect.js
- packages/design-system/src/components/MultiSelectField/style.scss
- packages/design-system/src/components/SelectField/ClearButton.js
- packages/design-system/src/components/SelectField/Select.js
- packages/design-system/src/components/SelectField/SelectField.md
- packages/design-system/src/components/SelectField/SelectList.js
- packages/design-system/src/components/SelectField/style.scss
- packages/design-system/src/interfaces/forms.d.ts
Some changes in input fields:
1.  Changed inputs height to fit the designs. All should be 36px. -> https://app.zeplin.io/project/5b4fb0903176d0d90e5b04f8/screen/5be9ac5eccaa613e8652da64
2. Added optional header in select list, -> https://app.zeplin.io/project/5def6564c8bd560826d74d74/screen/5df0d5fb49d73eaeaf831fe0
3. Do not render clear button, instead of hiding it.
> adjust inputs

- packages/design-system/src/components/Tab/style.scss
There were wrong hover and selected styles on `Tabs`, they were using `#000`.
> Tab - styling fix

- packages/design-system/src/components/InputField/InputField.js
- packages/design-system/src/components/MultiSelectField/MultiSelectField.js
- packages/design-system/src/components/NumericInputField/NumericInputField.js
- packages/design-system/src/components/SelectField/SelectField.js
- packages/design-system/src/components/TextAreaField/TextAreaField.js
- packages/design-system/src/components/TextField/TextField.js
- packages/design-system/src/components/TextField/style.scss
- packages/design-system/src/interfaces/buttonGroup.d.ts
- packages/design-system/src/interfaces/forms.d.ts
TextField labelAdornment property allows displaying a React node next to the label as a way to decorate the whole input element with an additional element like icon or tooltip trigger and etc.
The main motivation for adding this prop is to allow extending already existing text explanation for input with some possible interactive decoration elements. The label adornment is treated generically it only restricts the dimensions and layout but is more like a "render spot" for the consumer content rather than the actual element.
> TextField labelAdornment

- packages/design-system/src/components/SearchBar/SearchBar.js
- packages/design-system/src/components/SearchBar/style.scss
Jira: https://livechatinc.atlassian.net/browse/DS-121
Hey, according to the above task the close icon in search bar is disappearing quicker from the DOM than some helper function/hook a developer wants to use and it is causing problems. I've prepared a fix that icon is always visible in the DOM (`display: none/block`) and even if user will turn this icon on through dev console then nothing will happen (blocked handlers on this icon).
Moreover I'm trying new concept of `data-element` attributes to help user find elements inside given component. WDYT about this approach?
PS: In the code there are some prettier code formatting changes
> DS-121 Improve search bar close icon

- packages/design-system/src/components/TooltipNew/UserGuideTooltip.js
UserGuideTooltip were using `Element` directly which was not working with SSR (next.js in my case).
> Fix prop-types of UserGuideTooltip

- packages/design-system/src/components/Form/Form.js
- packages/design-system/src/components/Form/style.scss
if there is no labelText or helperText there is no need to render the tag with margin inside
> DS-144 Do not render not needed tag for header in Form component

- packages/design-system/CHANGELOG.md
- packages/design-system/package.json
- packages/design-system/src/components/NumericInputField/NumericInput.js
As title says, allow onFocus and onBlur handlers passed in props to execute
> Add onFocus and onBlur handlers to NumericInput

- packages/react-components/.storybook/preview-head.html
- packages/react-components/src/components/Button/Button.stories.tsx
- packages/react-components/src/components/FileUploadProgress/FileUploadProgress.stories.tsx
- packages/react-components/src/components/Loader/Loader.stories.tsx
- packages/react-components/src/components/Search/Search.stories.tsx
- packages/react-components/src/components/Switch/Switch.module.scss
- packages/react-components/src/components/Switch/Switch.spec.tsx
- packages/react-components/src/components/Switch/Switch.stories.tsx
- packages/react-components/src/components/Switch/Switch.tsx
- packages/react-components/src/components/Tag/Tag.stories.tsx
- packages/react-components/src/components/UploadBar/UploadBar.stories.tsx
- packages/react-components/src/stories/components/StoryDescriptor.tsx
Resolves #344 
- Lock icon added for the disabled state,
- Applied proper color tokens for `hover`, `enabled`, and `disabled` cases,
- Changed naming convention as `enabled/disabled` was easy to be confused with `checked (on)/unchecked (off)`,
- Added multiple stories representing the changes,
- I've used `--color-action-default-rgb` for `box-shadow`
- [Disabled On](https://613a8e945a5665003a05113b-muqgbybjhw.chromatic.com/?path=/story/components-switch--disabled-on)
- [Disabled Off](https://613a8e945a5665003a05113b-muqgbybjhw.chromatic.com/?path=/story/components-switch--disabled-off)
> #344 Handle Switch disabled state visually

- packages/react-components/src/components/Badge/Badge.module.scss
- packages/react-components/src/components/Badge/Badge.spec.tsx
- packages/react-components/src/components/Badge/Badge.stories.tsx
- packages/react-components/src/components/Badge/Badge.tsx
Resolves #341
The original issue assumed only the need to apply some styles, however, the component requires some bigger refactor in order to handle various variants. Changes applied:
- Added `kind` prop instead of `secondary` boolean
- Added `size` to handle 3 cases
- Added `type` to automatically handle `alert` and `dot` variants. I've ignored `new-message` and `extended` as for now I believe other forms of content should be handled externally.
- [Default](https://613a8e945a5665003a05113b-nhdgxclxti.chromatic.com/?path=/story/components-badge--default)
- [Sizes](https://613a8e945a5665003a05113b-nhdgxclxti.chromatic.com/?path=/story/components-badge--sizes)
- [Kinds](https://613a8e945a5665003a05113b-nhdgxclxti.chromatic.com/?path=/story/components-badge--kinds)
- …
> #341 Reorganize Badge component to reflect Figma designs

- packages/react-components/src/components/Input/Input.module.scss
- packages/react-components/src/components/Input/Input.stories.tsx
- packages/react-components/src/components/Input/Input.tsx
- packages/react-components/src/components/TagInput/TagInput.module.scss
- packages/react-components/src/components/TagInput/TagInput.stories.tsx
Resolves: #339 
Initially, the task assumed only adding missing background color tokens, however, I've also found out it requires some work around stories and other styles. Here's what changed:
* Added background and placeholder color tokens for `Input`
* Added background and disabled color tokens for `TagInput`
* Added `disabled` prop to `InputProps`
* Reorganized stories to cover sizes and states of Input components
* [Chromatic UI review](https://www.chromatic.com/build?appId=613a8e945a5665003a05113b&number=514)
* [Input](https://613a8e945a5665003a05113b-mtkyesnbym.chromatic.com/?path=/story/forms-input--default)
* [TagInput](https://613a8e945a5665003a05113b-mtkyesnbym.chromatic.com/?path=/story/forms-tag-input--default-tag-input)
**Optional:**
> #339 Apply missing tokens to Input and TagInput components

- packages/react-components/.storybook/preview-head.html
- packages/react-components/src/components/Avatar/Avatar.helpers.ts
- packages/react-components/src/components/Avatar/Avatar.module.scss
- packages/react-components/src/components/Avatar/Avatar.spec.tsx
- packages/react-components/src/components/Avatar/Avatar.stories.tsx
- packages/react-components/src/components/Avatar/Avatar.tsx
- packages/react-components/src/components/Avatar/index.ts
Resolves: #373 
Implements the `Avatar` component from scratch. During the development phase I made some decisions to be confirmed by the rest of the team:
* I decided to make the API more generic. For example instead of `kind: 'person' | 'group'` I've used `shape: 'circle' : 'rounded-square'`. A similar change was for the status, as not all products are chat-focused, so I avoided the `accepts chats` name.
* Figma project does not specify the behavior of rim in case of `rounded-square`, nevertheless, I implemented it.
* I'm a bit confused on how to address the position of the status icon as the design seems to do it differently for each size and square. I tried to follow that assumption with some slight modifications.
- [Avatar](https://feature-373--613a8e945a5665003a05113b.chromatic.com/? …
> #373 Avatar component

- packages/react-components/.storybook/preview.js
- packages/react-components/package.json
- packages/react-components/src/components/Toast/Toast.module.scss
- packages/react-components/src/components/Toast/Toast.spec.tsx
- packages/react-components/src/components/Toast/Toast.stories.tsx
- packages/react-components/src/components/Toast/Toast.tsx
- packages/react-components/src/foundations/shadow-token.ts
- packages/react-components/src/foundations/shadow.css
- packages/react-components/src/index.scss
- packages/react-components/src/index.ts
- packages/react-components/src/utils/story-parameters.ts
Resolves: #385
* Added basic `shadow` tokens
* Reorganized `Toast` styles (mostly simplified)
* Removed `notification` kind, fixed color tokens for `info` kind
* Added more advanced stories for `Toast`
* Added missing export of `Avatar`
* Renamed some `Toast` props to follow convention
https://feature-385--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #385 Change CloseIcon size and background colour for 'info' variant

- packages/react-components/src/components/Alert/Alert.tsx
Resolves: #377
* `Alert` now uses `large` size for `Icon` 
https://feature-377--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #377 Alert now uses 'large' size for Icon

- packages/react-components/src/components/Switch/Switch.spec.tsx
- packages/react-components/src/components/Switch/Switch.stories.tsx
- packages/react-components/src/components/Switch/Switch.tsx
Resolves: #386
- Introduced `state` prop with values of `regular`, `locked`, and `loading`.
- Removed `loading` boolean prop.
- `locked` and `loading` variants behave as disabled.
- In the `regular` state `disabled` availability has no icons.
https://feature-386--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #386 Separate disabled and locked states in Switch component

- packages/react-components/src/components/Badge/Badge.helpers.ts
- packages/react-components/src/components/Badge/Badge.spec.tsx
- packages/react-components/src/components/Badge/Badge.stories.tsx
- packages/react-components/src/components/Badge/Badge.tsx
Resolves: #382
* `Badge` has two new props: `count` and `max` with defaults set to `0` and `99`.
* `children` prop is no longer supported as only numeric values are allowed.
* `React.HTMLAttributes<HTMLSpanElement>` are now supported as additional props.
* https://feature-382--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #382 Handle only numeric values as Badge content. Support custom limit.

- .stylelintrc.json
- package-lock.json
- package.json
- packages/react-components/src/components/Button/Button.tsx
- packages/react-components/src/components/Button/index.ts
- packages/react-components/src/components/Card/Card.module.scss
- packages/react-components/src/components/Card/Card.spec.tsx
- packages/react-components/src/components/Card/Card.stories.tsx
- packages/react-components/src/components/Card/Card.tsx
Resolves: #390
Refactored `Card` component according to design in Figma. Main changes include:
* Visual update
* Support for expandable content
* Support for action buttons in component's footer
Additionally, I've introduced:
* [concentric-order](https://github.com/chaucerbao/stylelint-config-concentric-order#readme) for `stylelint`
* `stylelint` libraries updates
https://feature-390--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #390 Card component refactoring

- packages/react-components/src/components/Popover/Popover.module.scss
- packages/react-components/src/utils/StackingContextLevel.scss
Resolves: #[332](https://github.com/livechat/design-system/issues/332)
It seems to be enough to fix stuff like:
https://monosnap.com/file/agb5EyL9CrbJqO8E0vNQhtUAo6BYOo
https://613a8e945a5665003a05113b-iaeypnmfan.chromatic.com/
**Optional:**
> #332 z-index for Popover component

- packages/react-components/src/components/Popover/Popover.stories.tsx
- packages/react-components/src/components/Popover/Popover.tsx
Resolves #423
One of the teams has reported that the Popover component lacks options when it comes to placement.
This PR provides a way of passing options for flip() method available in floatingUI library
https://floating-ui.com/docs/flip
https://popover-more-options--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #423 Provide way of passing flip parameters to Popover component

- packages/react-components/src/components/Switch/Switch.spec.tsx
- packages/react-components/src/components/Switch/Switch.tsx
Resolves: #444
At the moment looks like there is no way to set either `aria-label` or `aria-labelledby` for checkbox input element inside the switch. 
I propose to add new optional property for Switch interface to allow setting accessible name (one of several ways to achieve it). 
I also removed test-id that seems to be some kind of leftover after moving components to new DS setup. I didn't find any usage of this `foo` test id in the repository. I think leaving it there was not intentional.
https://feature-v1-switch-accessibility-props--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> [Switch] Allow accessible name for switch input element

- packages/react-components/src/components/Button/Button.module.scss
Resolves: #440 and https://livechatinc.atlassian.net/browse/AA-13976
When we use buttons and add the margin, the button's highlights are not in the right place. I changed from `box-shadow` to the `filter: drop-shadow` property. 
Before: 
After: 
https://feature-AA-13976--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #440 Change on focus property from box shadow to filter

- packages/react-components/src/components/Picker/Picker.spec.tsx
- packages/react-components/src/components/Picker/Picker.stories.css
- packages/react-components/src/components/Picker/Picker.stories.tsx
- packages/react-components/src/components/Picker/PickerList.module.scss
- packages/react-components/src/components/Picker/PickerList.spec.tsx
- packages/react-components/src/components/Picker/PickerList.tsx
- packages/react-components/src/components/Picker/Trigger.tsx
- packages/react-components/src/components/Picker/TriggerBody.spec.tsx
- packages/react-components/src/components/Picker/TriggerBody.tsx
Resolves: #343 
Some changes related to the interface and logic of `Trigger` and `PickerList`, enabling the possibility to pass the own component as list item.
[Storybook](https://613a8e945a5665003a05113b-rghnsupxqz.chromatic.com/?path=/docs/components-picker--picker-with-options-as-custom-elements)
**Optional:**
> #343 Extend the Picker options interface and logic to enable passing the own component as item

- packages/react-components/src/components/Card/Card.module.scss
Resolves: #421 
The previous version of the Card component had its children positioned vertically, not horizontally. This change makes sure that the current version does not introduce a regression.
https://feature-421--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> [CARD] use default layout for nested components 

- packages/react-components/src/components/Card/Card.tsx
Resolves: #420 
Hide the Card header if the title is not provided.
https://feature-420--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> [Card] hide header if title not available

- packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
https://user-images.githubusercontent.com/58426925/212089848-24540f13-17fa-4d5a-b32c-5bd17ce15a90.mov
Proposition to add [aria-pressed](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed) attribute to inform screen reader and testing frameworks about currently selected option.
https://feature-{issue-number}--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> Add aria-pressed attribute to buttons inside segmented control

- packages/react-components/src/components/Picker/Picker.tsx
- packages/react-components/src/components/Picker/TriggerBody.tsx
- packages/react-components/src/components/Tag/Tag.tsx
Resolves: #482
We need to have a way to change "close" icon size on Tag. This is the way.
https://feature-482--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> Provide means for changing icon size used in Tag and by extension Picker component

- packages/react-components/src/components/Tab/Tab.module.scss
- packages/react-components/src/components/Tab/Tab.spec.tsx
- packages/react-components/src/components/Tab/Tab.stories.tsx
- packages/react-components/src/components/Tab/Tab.tsx
- packages/react-components/src/components/Tab/TabsWrapper.stories.tsx
Resolves: #399
Changes related to the `Tab` component:
- renamed the `description` prop to `count`, also changed the type of that prop to number (we don't want to allow to put anything to the counter)
- added the possibility to display the counter as a badge
- added missing functionality to set the `Tab` size
- added more stories do the `Tab` component
https://feature-399--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #399 [Tab] Improvements

- packages/react-components/src/components/Search/Search.module.scss
- packages/react-components/src/components/Search/Search.spec.tsx
- packages/react-components/src/components/Search/Search.stories.tsx
- packages/react-components/src/components/Search/Search.tsx
Resolves: #406
Changes related to the behavior of `isCollapsable` version of `Search`.
Some of the logic responsible for UI has been moved to the component container (background, borders, etc.), to make it easier to control in the `isCollapsable` version.
Loader has his own background to be better visible in the state `disabled` + `isLoading`.
Also added a separate story for the `isCollapsable` version, to show behavior with other, potential elements in the UI.
https://feature-406--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #406 - Search - adjusted logic and styles

- packages/react-components/src/components/Popover/Popover.stories.tsx
- packages/react-components/src/components/Popover/Popover.tsx
Resolves: #500 
A simple change that will allow passing the handler to be fired when `Popover` closes.
No tests and stories update at this moment, because component will be updated in the future.
https://feature-500--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #500 - Popover -  onClose prop to pass handler for popover close action

- packages/react-components/src/components/Picker/Picker.stories.tsx
- packages/react-components/src/components/Picker/Picker.tsx
- packages/react-components/src/components/Picker/PickerList.module.scss
- packages/react-components/src/components/Picker/PickerList.spec.tsx
- packages/react-components/src/components/Picker/PickerList.tsx
- packages/react-components/src/components/Picker/TriggerBody.module.scss
- packages/react-components/src/components/Picker/TriggerBody.tsx
Resolves: #479 #477 #395 
Some bug fixes:
- added ellipsis for long strings in `Trigger Body` (also added to list items)
- fixed the issue in `multi` mode, where items could be removed even with a disabled state by just blocking the possibility to click the "x" icon
- fixed the issue with selecting the items on a filtered list
https://feature-picker-fixes--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> #479 #477 #395 - Picker - bug fixes

- docs/customized-components/Menu.js
Modal with information about the deprecation of old DS components and documentation.
As I didn't find in the [React Styleguidist](https://react-styleguidist.js.org/) documentation any good example of how to put the banner which will be visible on every page, without destroying it, we decided to put the modal in the navigation menu which is visible everywhere.
> Modal with deprecated information for old ds

- packages/react-components/src/components/Alert/Alert.module.scss
- packages/react-components/src/components/Alert/Alert.stories.tsx
- packages/react-components/src/components/Alert/Alert.tsx
- packages/react-components/src/components/Avatar/Avatar.stories.tsx
- packages/react-components/src/components/Avatar/Avatar.tsx
- packages/react-components/src/components/Badge/Badge.tsx
Description for API props.
https://feature-{issue-number}--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> Badge - component api docs update

- packages/react-components/src/components/Tooltip/Tooltip.tsx
Resolves: #570 
Disabling pointer-events to avoid tooltip element blocking other DOM elements during long transition-delay animation.
https://feature-570--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> 570: Tooltip - disabling clicks on tooltip during animations

- packages/react-components/src/components/Popover/Popover.tsx
Resolves: #573
Adding closeOnEsc to the dependencies array of a hook to properly react on prop changes
https://feature-573--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> 573: reacting properly on closeOnEsc prop change

- packages/react-components/src/components/Picker/Picker.tsx
- packages/react-components/src/components/Picker/Trigger.tsx
Resolves: [DS-273](https://livechatinc.atlassian.net/browse/DS-273)
Adding openedOnInit prop; passthrough of the data-testid prop to trigger element
https://feature-DS-273--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
[DS-273]: https://livechatinc.atlassian.net/browse/DS-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DS-273: adding openedOnInit prop; passthrough of the data-testid prop to trigger element

- packages/react-components/src/components/Input/Input.spec.tsx
- packages/react-components/src/components/Input/Input.tsx
- packages/react-components/src/components/TagInput/TagInput.tsx
Resolves: #426
- Passing HTMLInput elements to TagInput component
- Removing hardcoded data-testid prop from Input component
https://feature-426--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> 426: DevEx Improvements in Input and Tag Input components

- packages/react-components/src/components/Popover/Popover.tsx
Fixing issue when closeOnEsc was wrongly memorized in eventHandlers
https://feature-573--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> 573: Popover - fix for closeOnEsc prop

- packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
- packages/react-components/src/components/Tooltip/Tooltip.tsx
Resolves: #597
Triggering onClose and onOpen callbacks when visibility changes on hover action
https://feature-597--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> 597: Tooltip - onOpen, onClose fixes

- packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
- packages/react-components/src/components/Tooltip/Tooltip.tsx
Resolves: #613 
- Fix redundand calls of `onOpen` & `onClose` callbacks
https://feature-613--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> Avoid redundand calls of onOpen and onClose callbacks

- packages/react-components/src/components/Checkbox/Checkbox.module.scss
Resolves: #634 
Removing `mask-size: cover` property to fix the Checkbox mask on Safari and Firefox browsers
https://feature-634--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> 634: Checkbox mask size issue on Safari and Firefox

- packages/react-components/src/components/Popover/Popover.module.scss
Resolves: #611 
Replacing Popover background color token with component-specific `--popover-background`.
https://feature-611--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
> Popover: replacing colour token

- packages/react-components/src/components/Checkbox/Checkbox.module.scss
- packages/react-components/src/components/Checkbox/Checkbox.stories.tsx
Fixing Checkbox component styling by reverting -webkit-mask line and adding a stylelint ignore to prevent styling from automatically removing this line. Also I've changed a corresponding story to control Checkbox component via arg control panel.
https://feature-checkbox-fix--613a8e945a5665003a05113b.chromatic.com/{link-related-to-the-story}
> Fixing Checkbox component styling

- packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
- packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
- packages/react-components/src/components/RadioButton/RadioButton.module.scss
Resolves: #566 
Added optional prop that will prevent closing the menu after the item click. It can be used to put the form-like elements to the menu like radio buttons or switch.
I also adjusted the `Radio button` styles to fit the design if implemented inside the menu.
https://feature-566--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--keep-open-on-item-click
> #566 - ActionMenu - Option to prevent closing when option is selected

- packages/react-components/src/themes/dark.scss
- packages/react-components/src/themes/legacy.scss
- packages/react-components/src/themes/light.scss
Resolves: #710 
Fix for missing `--popover-background` token values in all themes.
https://feature-710--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-popover--default
> #710 - Popover - Fix for missing token value used as background color

- packages/react-components/src/components/Alert/Alert.tsx
- packages/react-components/src/components/Tooltip/Tooltip.module.scss
- packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
- packages/react-components/src/components/Tooltip/components/Info.tsx
- packages/react-components/src/components/Tooltip/components/Interactive.tsx
- packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
- packages/react-components/src/components/Tooltip/helpers.ts
- packages/react-components/src/components/Tooltip/types.ts
Resolves: #728 
Change default button kinds for Interactive and User Guide.
https://feature-728--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-tooltip--tooltip-interactive
> #728 - Tooltip - Change default button kinds for Interactive and User Guide

- packages/react-components/src/components/Modal/Modal.tsx
- packages/react-components/src/components/Modal/StoriesComponents.tsx
- packages/react-components/src/components/Popover/Popover.stories.tsx
- packages/react-components/src/components/Popover/Popover.tsx
- packages/react-components/src/components/Toast/Toast.tsx
- packages/react-components/src/components/Toast/ToastWrapper.stories.tsx
- packages/react-components/src/components/Tooltip/index.ts
Fixes for non-text content of Modal, Toast, Popover components
Fix for Tooltip type export
https://feature-fixes-for-components-content--613a8e945a5665003a05113b.chromatic.com/{link-related-to-the-story}
> Fixing non-text content styling. Tooltip type exporting.

- packages/react-components/src/components/Tag/Tag.mdx
- packages/react-components/src/components/Tag/Tag.module.scss
- packages/react-components/src/components/Tag/Tag.spec.tsx
- packages/react-components/src/components/Tag/Tag.stories.tsx
- packages/react-components/src/components/Tag/Tag.tsx
Replacing leftIcon, rightIcon, avatar props with leftNode and rightNode
https://feature-tag-additional-nodes--613a8e945a5665003a05113b.chromatic.com
> Replacing leftIcon, rightIcon, avatar props with leftNode and rightNode

- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Resolves: #781 
When the first element on the list was a header element, or disabled element, when using the arrow up to select an element the logic crushes the app, trying to check an element with a negative index number.
This fix will return the last correct index number, if previous elements from the list are blocked (disabled, header)
https://feature-781--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--keep-open-on-item-click
> #781 - [ActionMenu] - Fix for selecting items by keyboard logic

- packages/react-components/src/components/Picker/TriggerBody.module.scss
- packages/react-components/src/components/Picker/TriggerBody.tsx
Resolves: #787 
Style fixes to prevent layout break for small container.
https://feature-787--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-picker--default
> #787 [Picker] - ui fix for small container

- packages/react-components/src/components/Avatar/Avatar.module.scss
Removed margin when rim is visible.
https://feature/avatar-with-rim-fix--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-avatar--sizes-with-rim
> [Avatar] - Fix for moving avatar when rim is visible

- packages/react-components/src/components/Tag/Tag.stories.tsx
- packages/react-components/src/components/Tag/Tag.tsx
Resolves: #771 
Change close icon size for `small` version of component.
This does not apply to icons because their size is controlled on the consumer side.
https://feature-771--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-tag--sizes
> #771 - Tag - Close icon size change for small component

- packages/react-components/src/components/Switch/Switch.spec.tsx
- packages/react-components/src/components/Switch/Switch.tsx
In controlled mode (when the on prop is passed) the component does not alter its internal state when being pressed.
https://feature-switch-fix--613a8e945a5665003a05113b.chromatic.com
> Switch - fix for controlled component mode

- packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
- packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Resolves: #807 
Changed the styles for the group header if that element is first on the menu list.
Added required `id` prop for component that will be used in the keyboard control logic. (this fixes the issue If there are multiple instantiations of that component in a single view).
Changed the styles for `focus` state, it will now work only for keyboard control.
https://feature-807--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--keep-open-on-item-click
> #807 - ActionMenu - Group header styles change, improved logic for keyboard control

- packages/react-components/src/components/Picker/PickerList.tsx
Resolves: #768 
Fix for the issue described in the task.
It was caused by the event listener for key down when the list is opened. By capturing the `enter` key, executed logic causes to throw the error, because it wants to refer to the selected item from the list, where there is any item selected.
https://feature-768--613a8e945a5665003a05113b.chromatic.com/?path=/docs/components-picker--docs
> #768 - Picker - Fix for TS error when input is empty and no item is selected

- packages/react-components/src/components/Picker/PickerList.tsx
Resolves: #820 
The issue was caused by incorrectly handling the `currentItemKey`, which shows the currently focused element when using the keyboard control while filtering the list.
https://feature-820--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-picker--default
> #820 - Picker - Fix for keyboard control issue after filtering the list

- packages/react-components/src/themes/design-token.ts
Adding missing color token SurfaceAccentEmphasisMediumPositive to DesignToken enum
https://feature-adding-missing-token--613a8e945a5665003a05113b.chromatic.com
> fix(DesignToken): adding missing colour token

- packages/react-components/src/themes/design-token.ts
Adding missing color token SurfaceAccentEmphasisMediumNegative in the enum.
https://feature-adding-missing-token--613a8e945a5665003a05113b.chromatic.com
> fix(DesignToken): adding missing color token

- packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
- packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
- packages/react-components/src/components/ActionMenu/constants.tsx
Change styles for divider, now it will be displayed after element with this flag set.
https://feature-action-menu-divider-fix--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--keep-open-on-item-click
> fix(ActionMenu): Change divider position after element with this flag

- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Resolves: #840 
Moving `className` prop to parent element in PromoBannerV2 component.
https://feature-840--613a8e945a5665003a05113b.chromatic.com
> fix(PromoBannerV2): moving className prop to parent element

- packages/react-components/src/components/TagInput/EmailTagInput.tsx
- packages/react-components/src/components/TagInput/TagInput.tsx
Resolves: #427 
- allowing passing additional props to TagInput; 
- adding inputClassName
https://feature-427--613a8e945a5665003a05113b.chromatic.com
> fix(EmailTagInput): Passing props to TagInput component

- packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
- packages/react-components/src/components/DetailsCard/DetailsCard.stories.tsx
- packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Added `rightNode` to put own element in the right side of the label.
https://feature-details-card-right-node--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-detailscard--example-usage
> feat[DetailsCard): Added rightNode to pass own element to the label

- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
- packages/react-components/src/components/Popover/Popover.tsx
- packages/react-components/src/components/Popover/types.ts
- packages/react-components/src/components/Tooltip/Tooltip.tsx
- packages/react-components/src/components/Tooltip/types.ts
Resolves: #899 
This change should give the possibility to solve the issues with rendering floating elements inside containers with `overflow: hidden` style, by using the `floatingStrategy` flag, that can set the position of floating element to `fixed`.
This change includes `Tooltip`, `ActionMenu` and `Popover` components.
https://feature-899--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-tooltip--default
> feat(Tooltip): Added flag to set the position strategy

- packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
- packages/react-components/src/components/DetailsCard/DetailsCard.spec.tsx
- packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Set `max-height` of content container, based on size of passed element.
Addes `onClick` prop, to pass own handler which will be executed on label click.
https://feature-details-card-height-improve--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-detailscard--example-usage
> feat(DetailsCard): Dynamic set max-height of expanded element based on content, added onClick prop to pass own handler on label click

- packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
- packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
Restored possibility to indicate the selected option on the list.
https://feature-action-menu-active-state--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--with-selected-options
> feat(ActionMenu): Possibility to check the selected options

- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Resolves: #893 
Flag to enable vertical mode without container queries.
New props to pass own styles to content containers.
https://feature-893--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-promobannerv2--default
> feat(PromoBannerV2): vertical mode, class name props for content containers

- packages/react-components/src/components/Button/Button.module.scss
- packages/react-components/src/components/Button/styles/size.scss
Resolves: #896
Fixing only-icon Button padding
https://feature-896--613a8e945a5665003a05113b.chromatic.com
> fix(Button): Fixing only-icon Button padding

- packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
- packages/react-components/src/components/DetailsCard/DetailsCard.stories.css
- packages/react-components/src/components/DetailsCard/DetailsCard.stories.tsx
- packages/react-components/src/components/DetailsCard/DetailsCard.tsx
Added possibility to pass own component as card label.
https://feature-details-card-custom-label--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-detailscard--example-usage
> feat(DetailsCard): Custom component as card label

- packages/react-components/src/components/Alert/Alert.module.scss
- packages/react-components/src/components/Alert/Alert.tsx
Resolves: #942
Change close button placement for the large container.
https://feature-942--613a8e945a5665003a05113b.chromatic.com
> fix(Alert): Close button placement for large container

- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
- packages/react-components/src/components/Alert/Alert.tsx
- packages/react-components/src/components/Avatar/Avatar.tsx
- packages/react-components/src/components/Modal/components/ModalCloseButton.tsx
- packages/react-components/src/components/Picker/types.ts
- packages/react-components/src/components/Tag/Tag.tsx
- packages/react-components/src/components/Tooltip/components/Info.tsx
- packages/react-components/src/components/Tooltip/components/Interactive.tsx
- packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx
- packages/react-components/src/utils/constants.ts
- packages/react-components/src/utils/index.ts
- packages/react-components/src/utils/types.ts
Adding aria-label to close buttons in components
https://feature-close-buttons-aria--613a8e945a5665003a05113b.chromatic.com
> fix(components): Adding aria-label to close buttons in components

- packages/react-components/src/components/Modal/Modal.module.scss
- packages/react-components/src/components/Modal/components/ModalBase.tsx
- packages/react-components/src/utils/StackingContextLevel.scss
Implementation of `FloatingOverlay` component from `floating-ui` as our modals overlay. It will allow to scroll down the whole overlay if the modal size is larger than user window.
https://feature-modal-overflow-scroll--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-modal--modal
> fix(Modal): Possibility to scroll down the overlay if modal is larger than window

- packages/react-components/src/components/Input/Input.tsx
- packages/react-components/src/components/TagInput/TagInput.tsx
- packages/react-components/src/components/Textarea/Textarea.tsx
Fix for wrong implemented typography component in the `Input`, `TagInput` and `Textarea`, that causes the unexpected reduction in input size inside the wrapper.
This changes fix that.
https://feature-input-typography-fix--613a8e945a5665003a05113b.chromatic.com
> fix(Input): Fixes for typography component usage in Input, TagInput and Textarea

- packages/react-components/src/components/Search/Search.module.scss
- packages/react-components/src/components/Search/Search.tsx
Resolves: #1037
Fix for the short input container after typo changes.
Added ellipsis for the input for long string, enabled by default.
https://feature-1037--613a8e945a5665003a05113b.chromatic.com
> fix(Search): fix for short input container, added ellipsis

- packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
- packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx
- packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
- packages/react-components/src/components/ActionMenu/ActionMenu.tsx
- packages/react-components/src/components/ActionMenu/types.ts
New prop `footer` that allows to pass own element, which will be displayed under the menu items list.
https://feature-action-menu-footer--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--with-footer
> feat(ActionMenu): Footer prop to display own element in the menu

- packages/react-components/src/index.ts
Currently, there is no export of `Skeleton` component when using TypeScript.
> fix(Skeleton): Fix missing export

- packages/react-components/src/components/Tooltip/Tooltip.module.scss
- packages/react-components/src/components/Tooltip/Tooltip.tsx
- packages/react-components/src/foundations/design-token.ts
- packages/react-components/src/stories/foundations/Color/data.ts
- packages/react-components/src/themes/dark.scss
- packages/react-components/src/themes/legacy.scss
- packages/react-components/src/themes/light.scss
Resolves: #965
Two fixes:
- inner container `overflow: hidden` to overflow content
- changed local arrow to `FloatingArrow` from `floating-ui`, added styles (created special `--tooltip-border-for-svg` token for arrow stroke)
https://feature-965--613a8e945a5665003a05113b.chromatic.com
> fix(Tooltip): UI fixes

- packages/react-components/src/components/Picker/hooks/usePickerItems.ts
In `multi` mode while filtering the list, selected items were not possible to remove if they were not on the list.
https://feature-picker-multi-item-delete-fix--613a8e945a5665003a05113b.chromatic.com
> fix(Picker): fix for item removing in multi picker while filtering

- packages/react-components/.storybook/preview-head.html
- packages/react-components/src/components/Button/Button.module.scss
- packages/react-components/src/components/Button/Button.stories.tsx
- packages/react-components/src/components/Button/styles/kind.scss
- packages/react-components/src/components/Button/types.ts
- packages/react-components/src/components/Icon/Icon.module.scss
- packages/react-components/src/components/Icon/Icon.tsx
- packages/react-components/src/components/Tooltip/Tooltip.module.scss
- packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
- packages/react-components/src/components/Tooltip/Tooltip.tsx
- packages/react-components/src/components/Tooltip/components/Interactive.tsx
- packages/react-components/src/components/Tooltip/helpers.ts
- packages/react-components/src/foundations/design-token.ts
- packages/react-components/src/stories/components/StoryDescriptor.tsx
- packages/react-components/src/stories/foundations/Color/Color.stories.mdx
- packages/react-components/src/stories/foundations/Color/data.ts
- packages/react-components/src/stories/foundations/Color/types.ts
- packages/react-components/src/themes/dark.scss
- packages/react-components/src/themes/legacy.scss
- packages/react-components/src/themes/light.scss
Correct color tokens for `FloatingArrow` in different tooltip kinds.
New story "Kinds" to show every possible tooltip kind.
Added new `Button` kinds (`plain-lock-black` and `text-lock-black`) to cover `Important` kind UI requirements.
Added new `Icon` kind (`lock-black`) to cover `Important` kind UI requirements.
Added new color tokens to cover new `Button` kinds requirements.
https://feature-tooltip-arrow-color-fix--613a8e945a5665003a05113b.chromatic.com
> fix(Tooltip): UI fixes for Interactive kind, arrow color fixes

- packages/react-components/src/components/Picker/Picker.mdx
- packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Resolves: #1103
Added the possibility to filter items by `secondaryText`.
Added info about how filtering works to docs.
https://feature-1103--613a8e945a5665003a05113b.chromatic.com
> fix(Picker): filtering by secondaryText

- package-lock.json
- packages/react-components/package.json
- packages/react-components/src/components/Picker/Picker.tsx
- packages/react-components/src/components/Picker/components/PickerList.tsx
- packages/react-components/src/components/Picker/constants.ts
- packages/react-components/src/components/Picker/hooks/useFloatingPicker.ts
- packages/react-components/src/components/Picker/types.ts
Resolves: #1098
- Changing calculation logic for initial height of the list
- updating virtuoso version
- adding minListHeight prop
https://feature-1098--613a8e945a5665003a05113b.chromatic.com
> fix(Picker): PickerList height initial value calculation

- packages/react-components/src/components/DatePicker/DatePicker.tsx
This fix should prevent to infinite loop update of the component, on `month` prop change when `toMonth` is set.
https://feature-date-picker-update-loop-fix--613a8e945a5665003a05113b.chromatic.com
> fix(DatePicker): prevent infinite update

- packages/react-components/src/components/Tag/Tag.tsx
Change HTML tag for close button in `Tag` component, to prevent button nesting errors in case, when component is rendered in the `Picker` with `multi-picker` mode.
https://feature-1071--613a8e945a5665003a05113b.chromatic.com
> fix(Tag): change element html tag to prevent button nesting errors

- packages/react-components/src/components/Popover/Popover.spec.tsx
> fix(Popover): tests updates

- packages/react-components/src/components/Tab/Tab.spec.tsx
- packages/react-components/src/components/Tab/Tab.tsx
Reverting Tab role change to avoid breaking of available tests in AA.
This change will be reintroduced in the new 2.0.0 version of the DS.
https://feature-revert-tab-role-change--613a8e945a5665003a05113b.chromatic.com
> fix(Tab): reverting role back to button

- packages/react-components/src/components/ActionBar/ActionBar.module.scss
- packages/react-components/src/components/Icon/IconsShowcase/style.scss
Resolves: #1192
Fixing mixed support error for CSS `start` values.
https://feature-1192--613a8e945a5665003a05113b.chromatic.com
> fix(ActionBar): changing start to flex-start values

- packages/react-components/src/components/Tooltip/Tooltip.spec.tsx
- packages/react-components/src/components/Tooltip/Tooltip.tsx
- packages/react-components/src/components/Tooltip/types.ts
Resolves: [Slack Thread](https://text.slack.com/archives/CA945NPQR/p1719228311436989) 
Adding the `triggerOnHover` prop to allow enabling both (onHover and onClick) handlers simultaneously.
https://feature-tooltip-hover-click-fix--613a8e945a5665003a05113b.chromatic.com
> fix(Tooltip): adding triggerOnHover prop to allow enabling both handlers

- packages/react-components/src/components/Picker/Picker.spec.tsx
- packages/react-components/src/components/Picker/Picker.stories.tsx
- packages/react-components/src/components/Picker/Picker.tsx
- packages/react-components/src/components/Picker/hooks/usePickerItems.ts
- Fixing callbacks execution ordering: onClose/onOpen callbacks will be executed after onSelect callback.
- Prevent onOpen/onClose callbacks from firing when the list is already opened/closed.
https://feature-picker-callbacks-fixes--613a8e945a5665003a05113b.chromatic.com
> fix(Picker): onClose, onOpen callbacks fixes

- packages/react-components/src/foundations/design-token.ts
- packages/react-components/src/stories/foundations/Color/data.ts
- packages/react-components/src/themes/dark.scss
- packages/react-components/src/themes/legacy.scss
- packages/react-components/src/themes/light.scss
Resolves: #1248
Adding new and updating existing colour tokens.
https://feature-1245--613a8e945a5665003a05113b.chromatic.com
> fix(DesignToken): updating tokens; adding new

- packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.module.scss
- packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
- packages/react-components/src/components/AppFrame/components/NavigationTopBar/types.ts
- styling no longer breaks when a className is added to the `.Alert` component
-  border radii fixed (6px -> 8px)
- the top bar is fixed to be in dark-mod
https://feature-navigation-top-bar-v2--613a8e945a5665003a05113b.chromatic.com
> fix(AppFrame): Fix several NavigationTopBar issues

- packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
- packages/react-components/src/components/AppFrame/components/NavigationTopBar/types.ts
self-explanatory
https://feature-navigation-top-bar-classname--613a8e945a5665003a05113b.chromatic.com
> feat(AppFrame): allow `classname` prop in NavigationTopBar

- packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx
- packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx
- packages/react-components/src/components/ProductSwitcher/types.ts
Adding textURL prop and locking switcher in dark mode.
https://feature-switcher-tweaks--613a8e945a5665003a05113b.chromatic.com
> fix(ProductSwitcher): lock in dark mode; add textUrl Prop

- packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
Resolves: #1309 
Added color token for a disabled button to show disabled state. Removed the `opacity` prop, which will solve the problem of displaying tooltips for disabled elements.
https://feature-1309--613a8e945a5665003a05113b.chromatic.com
> fix(ActionMenu): change opacity to color token for disabled item

- packages/react-components/src/components/Picker/Picker.tsx
- packages/react-components/src/components/Picker/components/PickerTriggerBody.tsx
- packages/react-components/src/components/Picker/types.ts
Resolves: #1124 
Adding optional inputProps parameter to allow direct access to the main input's attributes.
https://feature-1124--613a8e945a5665003a05113b.chromatic.com
> fix(Picker): adding optional inputProps

- packages/react-components/src/components/Accordion/Accordion.tsx
- packages/react-components/src/components/Accordion/components/AccordionMultilineElement.tsx
- packages/react-components/src/components/AppFrame/AppFrame.mdx
- packages/react-components/src/components/AppFrame/AppFrame.module.scss
- packages/react-components/src/components/AppFrame/AppFrame.spec.tsx
- packages/react-components/src/components/AppFrame/AppFrame.stories.css
- packages/react-components/src/components/AppFrame/AppFrame.stories.tsx
- packages/react-components/src/components/AppFrame/AppFrame.tsx
- packages/react-components/src/components/AppFrame/components/MobileNavigation/MobileNavigation.module.scss
- packages/react-components/src/components/AppFrame/components/MobileNavigation/MobileNavigation.spec.tsx
- packages/react-components/src/components/AppFrame/components/MobileNavigation/MobileNavigation.tsx
- packages/react-components/src/components/AppFrame/components/MobileNavigation/types.ts
- packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
- packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.spec.tsx
- packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
- packages/react-components/src/components/AppFrame/components/index.ts
- packages/react-components/src/components/AppFrame/stories-helpers.tsx
- packages/react-components/src/components/AppFrame/types.ts
- packages/react-components/src/hooks/helpers.ts
- packages/react-components/src/hooks/index.ts
- packages/react-components/src/hooks/types.ts
- packages/react-components/src/hooks/useHeightResizer.ts
- packages/react-components/src/hooks/useMobileViewDetector.ts
- packages/react-components/src/hooks/useSharedResizeObserver.ts
- packages/react-components/src/providers/AppFrameProvider.tsx
https://feature-undefined--613a8e945a5665003a05113b.chromatic.com
> feat(AppFrame): mobile view and MobileNavigation component (#1319)

- packages/react-components/src/components/AutoComplete/AutoComplete.stories.tsx
- packages/react-components/src/components/AutoComplete/AutoComplete.tsx
Prevents `Enter` key event bubbling while using the AutoComplete picker
https://fix-autocomplete-prevent-default--613a8e945a5665003a05113b.chromatic.com
> fix(AutoComplete): fix autocomplete behavior in forms by preventing submissions on Enter keypress

- packages/react-components/src/components/Accordion/Accordion.module.scss
- packages/react-components/src/components/Accordion/Accordion.stories.css
- packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel.module.scss
- packages/react-components/src/components/Accordion/components/AccordionAnimatedLabel.tsx
Define the label height based on child component
https://feature-1358--613a8e945a5665003a05113b.chromatic.com
> feat(Accordion): change label height based on child component

- packages/react-components/src/components/Avatar/Avatar.module.scss
- packages/react-components/src/components/Avatar/Avatar.tsx
- packages/react-components/src/components/Button/Button.tsx
- packages/react-components/src/components/InviteAgents/InviteAgents.mdx
- packages/react-components/src/components/InviteAgents/InviteAgents.module.scss
- packages/react-components/src/components/InviteAgents/InviteAgents.spec.tsx
- packages/react-components/src/components/InviteAgents/InviteAgents.stories.tsx
- packages/react-components/src/components/InviteAgents/InviteAgents.tsx
- packages/react-components/src/components/InviteAgents/helpers.ts
- packages/react-components/src/components/InviteAgents/index.ts
- packages/react-components/src/components/InviteAgents/types.ts
- packages/react-components/src/index.ts
- packages/react-components/src/utils/types.ts
New component: [FIGMA](https://www.figma.com/design/koantnx83TCyrM1dH6LqLx/Refresh-WIP?node-id=3017-62928&node-type=frame&m=dev)
https://feature-invite-agents--613a8e945a5665003a05113b.chromatic.com
> feat(InviteAgents): new component

- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.mdx
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.css
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx
- packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Resolves: #1326 
Adding new kind dark for PromoBannerV2
https://feature-1326--613a8e945a5665003a05113b.chromatic.com
> tweak(PromoBannerV2): new kind "dark" for PromoBannerV2 

- packages/react-components/src/components/InviteAgents/InviteAgents.module.scss
- packages/react-components/src/components/InviteAgents/InviteAgents.spec.tsx
- packages/react-components/src/components/InviteAgents/InviteAgents.stories.tsx
- packages/react-components/src/components/InviteAgents/InviteAgents.tsx
- packages/react-components/src/components/InviteAgents/helpers.ts
- packages/react-components/src/components/InviteAgents/types.ts
Implementing new tooltip design and changing IAgent type structure
https://feature-invite-agents-tooltip--613a8e945a5665003a05113b.chromatic.com
> feat(InviteAgents): new tooltip design

- packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss
- packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.spec.tsx
- packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.tsx
- packages/react-components/src/components/AppFrame/components/SideNavigationGroup/types.ts
Our `SideNavigationGroup` logic should open the menu if a child item is selected. With our approach with unmounting the hidden elements, the logic cannot find the active element, so the side menu stay closed with selected item inside.
With this change, we keep the menu open initially to give the logic the possibility to find the active elements, and if there is no active element, then the menu is closed.
https://feature-app-frame-side-nav-fix--613a8e945a5665003a05113b.chromatic.com
> fix(AppFrame): auto open/close side menu if child element is active

- packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.module.scss
- packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx
- packages/react-components/src/components/AppFrame/components/SideNavigationGroup/SideNavigationGroup.module.scss
- packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.module.scss
- packages/react-components/src/components/AppFrame/components/SideNavigationItem/SideNavigationItem.tsx
- packages/react-components/src/components/SearchInput/SearchInput.module.scss
- packages/react-components/src/components/SearchInput/SearchInput.tsx
- packages/react-components/src/hooks/useAnimations.ts
Side navigation group chevron color update for closed state.
Fix for horizontal scroll after hovering main nav item.
Change `useAppFrame` listener to remove after invoke.
https://feature-app-frame-bug-fixes--613a8e945a5665003a05113b.chromatic.com
> fix(AppFrame): nav bar scroll fix and sub nav chevron update

- packages/react-components/src/components/ProductSwitcher/ProductSwitcher.mdx
- packages/react-components/src/components/ProductSwitcher/constants.ts
TeamChat is ready to be shown as a default product now.
https://feature-default-teamchat--613a8e945a5665003a05113b.chromatic.com
> feat(ProductSwitcher): TeamChat as default product

- packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
- packages/react-components/src/hooks/useAnimations.ts
- packages/react-components/src/hooks/useSleepWakeSync.ts
The sleep/wake scenario in this hook, which was previously added as the fix for top bar alerts scenarios, caused incorrect state change for other components that don't use a controlled state when the user lefts the browser tab. This change adds a conditional flag to enable this feature and is currently used for the top bar notifications components only.
Also added the dedicated hook for that, as it could be improved in the future and brings more code consistency in the hooks.
https://feature-use-animations-fix--613a8e945a5665003a05113b.chromatic.com
> fix(useAnimations): flag to enable sleep wake scenarios
