livechat/design-system

src/components/Tab/Tab.js, src/components/Tab/Tab.md
When `description` property is equal `0` `Tab` component is not rendering properly :(
=> Tab component description fix

src/components/Toast/style.scss
=> DS-72 fixed toast align on ie/safari/ff

CHANGELOG.md, package.json
_Release: 2019-07-15_
- `Toast` component styles fix for long action names
- `Switch` interface change - removing redundant onChange property
=> Release v0.4.3

src/components/Button/Button.js, src/components/Button/__snapshots__/Button.test.js.snap, src/components/Button/style.scss
Reverts livechat/design-system#98
=> Revert "fixed btn line height"

CHANGELOG.md, package.json
_Release: 2019-08-05_
- new `ButtonGroup` and `UserGuideTooltip` components
- adding themes to `PopperTooltip` and `CssTooltip` - 'invert' and 'important'
- fixing `RadioButton` and `CheckboxField` - IE11 styles issue
- adding missing form components interfaces
=> Release v0.4.4

src/components/NumericInputField/NumericInput.js, src/components/NumericInputField/__snapshots__/NumericInput.test.js.snap
Buttons should have type default as "button" to avoid submitting on click
=> Numeric input html improvement

src/components/CheckboxField/Checkbox.js, src/components/CheckboxField/style.scss
Right now if you want to use css only from DS, then you need to have a JS controll on checkbox classes to show properly state. Right now DS checkbox based on native HTML states.
=> Change checkbox structure to allow good work for alone HTML/CSS

CHANGELOG.md, package.json
- handling error in field group (#105)
- `UserGuideTooltip` - allow custom scrollable wrapper (#108)
- `forwardRef` enabled for `TextArea` and `TextAreaField` (#109)
- change checkbox structure to allow good work for alone HTML/CSS (#106)
- `NumericInput` - adding missing type attribute to buttons (#107)
- fixing `InAppMessage` footer styles issue on mobile devices (#111)
---
=> release v0.4.5

docs/Introduction.md, src/components/Card/style.scss
Made padding to be 18px all around.
Before: <img width="543" alt="Screenshot 2019-08-27 at 11 12 12" src="https://user-images.githubusercontent.com/3074083/63758379-f8325b00-c8bb-11e9-86c1-0c94cb98005c.png">
After: <img width="487" alt="Screenshot 2019-08-27 at 11 11 56" src="https://user-images.githubusercontent.com/3074083/63758388-fb2d4b80-c8bb-11e9-99a1-8c24172087c6.png">
=> Fix Card padding

docs/customized-components/Button.js, package.json, src/components/Button/Button.js, src/components/Button/Button.md, src/components/Button/style.scss, src/components/ButtonGroup/ButtonGroup.js, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap, src/components/ButtonGroup/style.scss, src/components/InAppMessage/InAppMessageFooter.js, src/docs/ComponentHtmlMarkup.js, src/interfaces/buttons.d.ts
**Design**
https://zpl.io/VYBq7xk
**Description**
- changing the border color of basic default Button
- using current styles in the Secondary Button
**NOTE**
- it requires a minor release (v0.6.0) cause the change is gonna affect UI of Apps using DS
=> Buttons - UI changes

src/components/Button/Button.js, src/components/Button/Button.md, src/components/Button/style.scss, src/interfaces/buttons.d.ts
- fixing buttons line-height
- adding svg icon support
JIRA: https://livechatinc.atlassian.net/browse/DS-76
=> Feature/DS-76 Fixing button line-height, adding svg icon support

src/components/Tab/style.scss
I've adjusted tabs styled according to designs and internal discussion on slack: https://livechat.slack.com/archives/CA945NPQR/p1561102438000100
Designs: https://app.zeplin.io/project/5c4ec1443fcf8345e74aafb5/screen/5c6edc6a6d6dc44097589998
=> Adjust tabs styles

CHANGELOG.md, package.json, src/components/Modal/ModalCloseButton.js, src/components/Switch/Switch.js, src/interfaces/switch.d.ts
_Release: 2019-10-09_
- `Switch` ts types fix (#133) - it was not possible to use ie. disabled attribute in ts projects
- fixing `Modal` close button type (#135)
---
=> Release 0.5.3

CHANGELOG.md, package.json, src/components/UploadBar/style.scss
_Release: 2019-10-10_
- UploadBar - fixing scroll issue on old browsers (#134)
---
=> Release v0.5.5

CHANGELOG.md, package.json, src/components/TextField/TextField.md, src/components/index.js, src/interfaces/forms.d.ts, styleguide.config.js
_Release: 2019-10-14_
- Exporting TextField component (#142)
---
=> Release 0.5.6

packages/design-system/src/components/ButtonGroup/ButtonGroup.js, packages/design-system/src/components/ButtonGroup/ButtonGroup.md, packages/design-system/src/components/ButtonGroup/ButtonGroup.test.js, packages/design-system/src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap, packages/design-system/src/components/ButtonGroup/style.scss, packages/design-system/src/components/index.js, packages/design-system/src/interfaces/buttonGroup.d.ts
new controlled (and group) button styles:
=> Controlled button styles

packages/design-system/CHANGELOG.md, packages/design-system/package-lock.json, packages/design-system/package.json, packages/design-system/src/components/InputField/style.scss, packages/design-system/src/components/MultiSelectField/MultiSelect.js, packages/design-system/src/components/MultiSelectField/style.scss, packages/design-system/src/components/SelectField/ClearButton.js, packages/design-system/src/components/SelectField/Select.js, packages/design-system/src/components/SelectField/SelectField.md, packages/design-system/src/components/SelectField/SelectList.js, packages/design-system/src/components/SelectField/style.scss, packages/design-system/src/interfaces/forms.d.ts
_Release: 2020-02-19_
- Inputs - adjust height
- Numeric Input - fix handling min & max values
- SelectField - possibility to add header in the items list
=> @livechat/design-system@0.7.0

package-lock.json, packages/colors/package-lock.json, packages/design-system/package-lock.json, packages/design-system/src/interfaces/tooltipNew.d.ts
Changed onClick interface for CSSTooltip
=> DS-115 Changed onClick interface for CSSTooltip

packages/design-system/src/components/Button/Button.js, packages/design-system/src/components/Button/Button.md, packages/design-system/src/components/Button/__snapshots__/Button.test.js.snap, packages/design-system/src/components/Button/style.scss, packages/design-system/src/components/Loader/style.scss
Added new props that allow adding a label while the button is in the loading state.
=> (DPS-1607) New props in button - loaderLabel

packages/design-system/src/scss/variables/colors.scss
Primary color should be `#424d57`, not `#424d59`, so I'm correcting that
=> proper primary color

packages/design-system/src/components/Modal/ActionModal.md, packages/design-system/src/components/NumericInputField/NumericInput.js, packages/design-system/src/components/NumericInputField/__snapshots__/NumericInput.test.js.snap, packages/design-system/src/interfaces/forms.d.ts
- fixing the type
- little optimization of rendering
=> Fixing NumericInput width property type

packages/design-system/src/components/index.js
=> add promo export

packages/design-system/src/components/Promo/style.scss
Taking into account that the css size matters we can improve it a little by avoiding duplication if possible.
=> Improving css styles of Promo component

packages/design-system/src/components/Promo/style.scss
=> promo design review

packages/design-system/package.json, packages/design-system/src/components/Banner/Banner.md, packages/design-system/src/components/Banner/style.scss, packages/design-system/src/components/Promo/Promo.js, packages/design-system/src/components/Promo/Promo.md, packages/design-system/src/components/Promo/__snapshots__/Promo.test.js.snap, packages/design-system/src/components/Promo/style.scss
* more place for text
* 20px margin on the right of img
=> promo design review v2

packages/design-system/src/components/TooltipNew/PopperTooltip.js
added type button to the button of popper tooltip close button
=> added type button to button of popper tooltip close button

packages/design-system/src/components/DatePicker/DatePicker.js
other solution for a problem described here: https://github.com/livechat/design-system/pull/209. This solution will require only patch version release (no breaking changes)
=> [DatePicker] Adding missing month change handler fallback

packages/design-system/package-lock.json, packages/design-system/package.json, packages/design-system/src/components/SearchBar/SearchBar.js, packages/design-system/src/components/SearchBar/SearchBar.md, packages/design-system/src/components/SearchBar/index.js, packages/design-system/src/components/SearchBar/style.scss, packages/design-system/src/components/index.js, packages/design-system/src/interfaces/forms.d.ts, packages/design-system/src/scss/variables/colors.scss, setup.js, styleguide.config.js
**Jira:**
https://livechatinc.atlassian.net/browse/DS-7
**Description:**
Search bar with some options like:
- `controlled/uncontrolled` option (either setting state directly in component or passing value from parent component)
- `compact mode` - either for mobile or smaller screen designs
- `loading/error`- to further improve component -> display `error` or `loading` state (they need to be passed from above)
- `debounceTime` - to stop abusing search bar and lets you query only by specific number of `ms`
- `onChange/onSubmit` options - to have two modes: by either allowing to search by `enter` (onSubmit) or just via typing (maybe with debounced option to enhance user experience)
- `onClear` - when we want user to clear input, but don't make a search
- `onKeyDown(event)` - we want to allow …
=> DS-7 SearchBar component

packages/design-system/CHANGELOG.md, packages/design-system/package-lock.json, packages/design-system/package.json, packages/design-system/src/components/SearchBar/SearchBar.js, packages/design-system/src/components/SearchBar/style.scss
- DS-121 Improve search bar close icon (#214)
=> @livechat/design-system@0.11.1

docs/Introduction.md
from `sketch://add-library/cloud/zb2DM` to `sketch://add-library/cloud/75e54498-85b7-45b5-a03f-d17292e48714` based on: https://sketch.cloud/s/75e54498-85b7-45b5-a03f-d17292e48714
=> updated sketch download file

docs/Introduction.md
from `sketch://add-library/cloud/zb2DM` to `sketch://add-library/cloud/75e54498-85b7-45b5-a03f-d17292e48714` based on: https://sketch.cloud/s/75e54498-85b7-45b5-a03f-d17292e48714
=> Updated sketch download file (#226)

packages/design-system/src/components/InputField/Input.js, packages/design-system/src/components/InputField/InputField.js, packages/design-system/src/components/InputField/InputField.md, packages/design-system/src/components/InputField/style.scss, packages/design-system/src/components/TextAreaField/TextArea.js, packages/design-system/src/components/TextAreaField/TextAreaField.js, packages/design-system/src/components/TextAreaField/TextAreaField.md, packages/design-system/src/components/TextAreaField/style.scss, packages/design-system/src/components/TextField/TextField.js, packages/design-system/src/components/TextField/style.scss, packages/design-system/src/interfaces/forms.d.ts
As bonus - increase width to 100% of textarea and input elements. It's an breaking change but I believe it's needed
The same thing was developed in https://github.com/livechat/design-system/pull/246. Due to some bugs there I want to propose a different approach
=> Handle inline label right node

packages/design-system/src/components/InputField/Input.js, packages/design-system/src/components/InputField/InputField.md
https://livechatinc.atlassian.net/browse/DS-128
=> prop types for input

packages/design-system/src/interfaces/forms.d.ts
Extend INumericInputProps interface with `onFocus` and `onBlur` optional props
=> Extend INumericInputProps interface

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/NumericInputField/NumericInput.js
=> Fix types for numeric input

packages/react-components/src/components/Tag/Tag.module.scss
https://livechatinc.atlassian.net/browse/DS-197
Not every decor tokens are used in Figma, so I've tried to follow the pattern from those tags where decor tokens are used:
`--decor-[color][value]`
=> DS-197 - decor tokens for Tag

packages/design-system/CHANGELOG.md, packages/design-system/package.json, packages/design-system/src/components/SelectField/SelectHead.js, packages/design-system/src/components/SelectField/index.js, packages/design-system/src/components/index.js, packages/design-system/src/interfaces/forms.d.ts
- Exports sub-components of SelectField (#328)
- TabIndex Parameterization in SelectHead Component (#328)
=> Exports sub-components of Select Component

packages/icons/package-lock.json, packages/react-components/package-lock.json, packages/react-components/package.json, packages/react-components/src/components/Popover/Popover.spec.tsx, packages/react-components/src/components/Popover/Popover.stories.css, packages/react-components/src/components/Popover/Popover.stories.tsx, packages/react-components/src/components/Popover/Popover.tsx
Popper is dead - long live Floating UI.
No design changes.
=> DS-205 Replace Popper with FloatingUI in Dropdown component

.github/pull_request_template.md
=> Pull request template concept

packages/react-components/src/components/PromoBanner/PromoBanner.module.scss
Resolves: #340 
A simple change in styles to standardize with the designs
- [Storybook](https://613a8e945a5665003a05113b-nkcweewpzn.chromatic.com/?path=/docs/components-promobanner--promo-banner)
**Optional:**
=> #340 Change font-size for content and header in PromoBanner to fit with designs

README.md
Resolves: #352 
Update of the README file, which includes the details related to instructions on how to setup the project.
null
**Optional:**
=> update README that includes the details how to setup the project

packages/react-components/src/components/Textarea/Textarea.module.scss, packages/react-components/src/components/Textarea/Textarea.spec.tsx, packages/react-components/src/components/Textarea/Textarea.stories.tsx, packages/react-components/src/components/Textarea/Textarea.tsx, packages/react-components/src/components/Textarea/index.ts, packages/react-components/src/index.ts
Resolves: #404
The new `Textarea` component.
- [Storybook](https://613a8e945a5665003a05113b-jofhkrqabr.chromatic.com/?path=/docs/forms-textarea--default)
**Optional:**
=> #404 Textarea component

packages/react-components/src/components/Picker/Picker.tsx
Simple and quick fix after unifying the interfaces related to the size of the components.
**Optional:**
=> Interface fix for Picker

packages/react-components/src/components/DatePicker/DatePicker.module.scss, packages/react-components/src/components/Toast/Toast.module.scss
Created ad-hoc to fix styles formatting preventing deploy.
https://feature-{issue-number}--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Styles formatting

packages/react-components/src/components/Icon/Icon.tsx, packages/react-components/src/components/SegmentedControl/SegmentedControl.stories.tsx, packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
Resolves: #467
The need for SegmentedControl to be able to display icons next to a button has emerged. This PR facilitates that.
https://feature-467--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> [SegmentedControl] provide means to show icon in segmented control

packages/react-components/src/components/Button/Button.spec.tsx
=> fix for button test

packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Tag/Tag.tsx, packages/react-components/src/stories/components/IconsShowcase.tsx
Had to change icon type that is used across DS.
=> changed icon type across DS

packages/react-components/src/components/Card/Card.module.scss, packages/react-components/src/components/Picker/index.ts, packages/react-components/src/components/Tag/Tag.module.scss
This is a PR that fixes few obstacles that we have encountered during introduction of new DS to AA.
=> [fixes] Card width, Tag background color, Picker interface

packages/react-components/src/components/SegmentedControl/index.ts
SegmentedControl missed its type.
=> SegmentedControl - export missing type

packages/react-components/.storybook/main.js, packages/react-components/package-lock.json, packages/react-components/package.json
Added the plugin which will enable the "Accessibility" option in our Storybook stories.
It will give us feedback about our components `a11y` compatibility
=> accessibility addon for Storybook

packages/react-components/src/components/Badge/Badge.module.scss, packages/react-components/src/components/Badge/Badge.stories.tsx
Resolves: #465 
Just a little fix in styles, preventing the badge size change while there is a single digit.
https://feature-465--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #465 - Badge - visual bug fix + story update

packages/react-components/src/components/Alert/Alert.tsx
Resolves: #451 
Possibility to pass additional props (like data-testid) to the component.
https://feature-451--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #451 - Alert - Possibility to pass additional props (like data-testid) to the component

packages/react-components/src/components/Avatar/Avatar.module.scss, packages/react-components/src/components/Badge/Badge.module.scss, packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Progress/ProgressBar.module.scss, packages/react-components/src/components/Progress/ProgressCircle.module.scss, packages/react-components/src/components/Switch/Switch.module.scss, packages/react-components/src/stories/components/ColorTokens.tsx, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/design-token.ts, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
https://feature-new-tokens--613a8e945a5665003a05113b.chromatic.com/
=> New design tokens

packages/react-components/src/stories/components/ColorTokens.tsx, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/design-token.ts, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
=> Tokens update

packages/react-components/src/components/Tooltip/Info.tsx, packages/react-components/src/components/Tooltip/Interactive.tsx, packages/react-components/src/components/Tooltip/Tooltip.module.scss, packages/react-components/src/components/Tooltip/Tooltip.stories.tsx
Resolves: #511 
Let the interactive tooltip get data for buttons.
https://feature-511--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #511 - Tooltip - let interactive tooltip get data for buttons

packages/react-components/src/components/Button/Button.tsx
Possibility to pass the ref to the button.
https://feature/ref-for-button--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Ref for button component

packages/react-components/src/themes/legacy.scss
Updated token values for `Legacy`
https://feature-DS-247--613a8e945a5665003a05113b.chromatic.com/
=> legacy tokens update

packages/react-components/src/components/ActionMenu/ActionMenu.module.scss, packages/react-components/src/components/ActionMenu/ActionMenu.spec.tsx, packages/react-components/src/components/ActionMenu/ActionMenu.stories.css, packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx, packages/react-components/src/components/ActionMenu/ActionMenu.tsx, packages/react-components/src/components/ActionMenu/ActionMenuDoc.mdx, packages/react-components/src/components/ActionMenu/ActionMenuDocs.mdx, packages/react-components/src/components/ActionMenu/constants.tsx, packages/react-components/src/components/ActionMenu/index.ts
Resolves: #381 
`ActionMenu` is a new component that gives the ability to quickly implement a menu-type UI elemtn with support for keyboard controls.
https://feature-381--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #381 - ActionMenu - Add new component

packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx
Resolves: #526 
New Subtle kind for button. 
Based on designs: 
Light - [Product Components](https://www.figma.com/file/2pFu80PXO5A2tfyrAGnx91/Product-Components?node-id=1534-201&t=3uvnWVYQTlNulpjg-4)
Dark - [[DARK] Product Components](https://www.figma.com/file/TT0jGHgNAlqpFfkTYZMKND/%5BDARK%5D-Product-Components?node-id=1534-201&t=rJoXEwciOSaJJKgF-4)
https://feature-526--613a8e945a5665003a05113b.chromatic.com/
=> #526 - [Button] - Add new kind "Subtle" 

packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/light.scss
Updated hex values for specific tokens.
https://feature-ds-260--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> DS-260 - New tokens values

packages/react-components/src/index.ts
Missed component export in index file.
https://feature-action-menu-export-fix--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Added missing ActionMenu export

packages/react-components/src/components/Alert/Alert.module.scss, packages/react-components/src/components/Alert/Alert.stories.tsx, packages/react-components/src/components/Alert/Alert.tsx
Description for API props.
https://feature-alert-api-doc-update--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Alert - component api docs update

packages/react-components/src/components/Alert/Alert.module.scss, packages/react-components/src/components/Alert/Alert.stories.tsx, packages/react-components/src/components/Alert/Alert.tsx, packages/react-components/src/components/Avatar/Avatar.stories.tsx, packages/react-components/src/components/Avatar/Avatar.tsx
Description for API props.
https://feature-avatar-api-doc-update--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Avatar - component api docs update

packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx
Description for API props.
https://feature-button-api-doc-update--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Button - component api docs update

packages/react-components/src/components/Popover/Popover.stories.tsx, packages/react-components/src/components/Popover/Popover.tsx
Resolves: #536 
Added the possibility to disable closing popover by pressing the `esc` key.
Added descriptions for component API props and updated documentation.
https://feature-536--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #536 - Popover - Add param to disable closing by esc press, docs update

packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/Picker/Picker.tsx, packages/react-components/src/components/Picker/Trigger.tsx
Resolves: #535 
Added the possibility to hide clear button, if options are selected.
Added descriptions for component API props and updated documentation.
https://feature-535--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #535 - Picker - Added possibility to hide clear button, docs improvements

packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx
Resolves: #543 
Introduce `kind="float"` button to DS. 
https://feature-543--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #543 - Button -  Create Float button

packages/react-components/src/components/Alert/Alert.module.scss, packages/react-components/src/components/Alert/Alert.spec.tsx, packages/react-components/src/components/Alert/Alert.stories.tsx, packages/react-components/src/components/Alert/Alert.tsx, packages/react-components/src/foundations/spacing.css
Resolves: #546 
- Added optional CTA buttons
- Changed the logic to set the correct `Alert` layout depending on container width
- Updated documentation: description for API props, changes in stories
- Added new `spacing token`
https://feature-546--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #546 - Alert - Improvements: optional CTA buttons, documentation update

packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx
Resolves: #548 
- New `dotted` variant
- correct `large` size height and width (in icon only variant)
- fix with hover state on blocked button in `plain` variant
https://feature-548--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #548 - Button - New button variant, UI fixes

packages/react-components/src/components/Textarea/Textarea.spec.tsx, packages/react-components/src/components/Textarea/Textarea.tsx
Resolves: https://livechatinc.atlassian.net/browse/DS-274
Add onfocus and onblur to Texarea component
https://feature-ds-274--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> DS-274: Add onfocus and onblur to Texarea component

packages/react-components/src/components/Picker/Picker.tsx
Resolves: https://livechatinc.atlassian.net/browse/DS-272
Added `options` to dependency array
https://feature-ds-272--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Add `options` to dependency list in `Picker` component

packages/react-components/src/components/Input/Input.module.scss, packages/react-components/src/components/Input/Input.stories.tsx, packages/react-components/src/components/Input/Input.tsx
Resolves: #553 
UI fixes + docs update
https://feature-553--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #553 - Input - UI fixes + docs update

packages/react-components/src/components/TagInput/TagInput.module.scss, packages/react-components/src/components/TagInput/TagInput.tsx
Resolves: #552 
UI fixes + docs update
https://feature-552--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #552 - Tag/Email Input - UI fixes + docs update

packages/react-components/.storybook/preview.js, packages/react-components/src/components/Picker/PickerList.module.scss, packages/react-components/src/foundations/color-scheme.css, packages/react-components/src/index.scss
Resolves: #569
Adds color-scheme attribute to PickerList to change color of the scrollbars when theme is changing
https://feature-569--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #569 - Picker - Adding dark mode support for scrollbars

packages/react-components/src/components/Tag/Tag.module.scss, packages/react-components/src/components/Tag/Tag.stories.tsx, packages/react-components/src/components/Tag/Tag.tsx
Resolves: #561 
Some UI changes and docs update.
https://feature-561--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #561 - Tag - UI fixes, docs update

packages/react-components/src/components/DatePicker/DatePicker.module.scss
Resolves: #551 
UI fixes.
https://feature-551--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #551 - DatePciker - UI fixes

packages/react-components/src/components/Search/Search.module.scss, packages/react-components/src/components/Search/Search.tsx
Resolves: #559 
UI fixes + docs update
https://feature-559--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #559 - Search - UI fixes + docs update

packages/react-components/src/components/SegmentedControl/SegmentedControl.module.scss, packages/react-components/src/components/SegmentedControl/SegmentedControl.tsx
Resolves: #560 
UI fixes + docs update.
https://feature-560--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #560 - SegmentedControl - UI fixes + docs update

packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/Picker/Trigger.module.scss, packages/react-components/src/components/Picker/TriggerBody.module.scss
Resolves: #577
Improving paddings for Trigger and TriggerBody components
https://feature-577--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> 577: Improving paddings for Trigger and TriggerBody components

packages/react-components/src/components/PromoBanner/PromoBanner.module.scss, packages/react-components/src/components/PromoBanner/PromoBanner.tsx
Resolves: #558 
UI fixes + docs update
https://feature-558--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #558 - PromoBanner - UI fixes + docs update

packages/react-components/src/components/Picker/PickerList.module.scss
Resolves: #521
Setting horizontal scroll in PickerList as auto
https://feature-521--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> 521: Picker - setting horizontal scroll in PickerList as auto

packages/react-components/src/components/Picker/PickerList.module.scss
Resolves: #601 
Removed hardcoded value and used correct token.
https://feature-601--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #601 - Picker - Update box-shadow value

packages/react-components/src/components/Tooltip/Interactive.tsx, packages/react-components/src/components/Tooltip/Tooltip.module.scss
Resolves: #562 
UI fixes for `Tooltip`
https://feature-562--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #562 - Tooltip - Ui fixes

packages/react-components/src/components/FieldDescription/FieldDescription.module.scss
Resolves: #549 
UI fixes for `Checkbox`.
https://feature-549--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #549 - Checkbox - UI fixes

packages/react-components/src/components/Button/Button.module.scss
Resolves: #604
Updating color token for Plain button
https://feature-604--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Updating color token for plain button

packages/react-components/src/themes/legacy.scss
Resolves: #600 
Updating content-basic-gradient-01 token for Legacy theme
https://feature-600--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Updating content-basic-gradient-01 token for Legacy theme

packages/react-components/src/themes/light.scss
Resolves: #590
Updating color token `--surface-invert-primary` for light theme.
https://feature-590--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Updating color token for light theme

packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/design-token.ts, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #599 
Adding new color tokens: SurfaceGradient01 and SurfaceGradient02
https://feature-599--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Adding new color tokens: SurfaceGradient01 and SurfaceGradient02

packages/react-components/src/components/Picker/PickerList.tsx
Resolves: #605
Updating "Check" icon color for selected Picker Item
https://feature-605--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Updating "Check" icon color for selected Picker Item

packages/react-components/src/components/Tooltip/Tooltip.tsx
Firing open-close callbacks for managed components
https://feature-tooltip-callbacks-improvement--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> Firing open-close callbacks for managed components

packages/react-components/package-lock.json, packages/react-components/package.json, packages/react-components/src/components/Popover/Popover.tsx, packages/react-components/src/components/Tooltip/Tooltip.tsx, packages/react-components/vite.config.ts
- Fixing the path for TS declaration files.
- Removing `nullish coalescing operator` as a temporary solution to passthrough compatibility issues with apps which still support older browsers.
=> Fixes for build process

packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/Picker/Trigger.module.scss, packages/react-components/src/components/Picker/Trigger.tsx, packages/react-components/src/components/Picker/TriggerBody.module.scss, packages/react-components/src/components/Picker/TriggerBody.tsx
Resolves: #557 
UI fixes. Some logic changed to cover `single` and `multi` mode cases.
https://feature-557--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #557 - Picker - UI fixes

packages/react-components/src/components/Tooltip/Info.tsx, packages/react-components/src/components/Tooltip/Tooltip.module.scss, packages/react-components/src/components/Tooltip/helpers.ts
Resolves: #626 
UI fixes for `Tooltip Info`
https://feature-626--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #626 - Tooltip - UI fixes

packages/react-components/src/components/Progress/ProgressBar.module.scss, packages/react-components/src/components/Progress/ProgressCircle.module.scss
Resolves #637
- Replacing background color token for ProgressBar
- Replacing background color token for ProgressCircle
- Removing unused styles in ProgressCircle
https://feature-637--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> 637: ProgressCircle and ProgressBar UI improvements

packages/react-components/src/components/Alert/Alert.module.scss, packages/react-components/src/components/Alert/Alert.tsx
Resolves: #642 
Updated tokens for component styles.
https://feature-642--613a8e945a5665003a05113b.chromatic.com/
**Optional:**
=> #642 - Alert - New tokens for all alert kinds

packages/react-components/src/components/ActionMenu/ActionMenu.mdx, packages/react-components/src/components/ActionMenu/ActionMenu.stories.tsx
Fix for missing API props in documentation.
https://feature-action-menu-docs-fix--613a8e945a5665003a05113b.chromatic.com/?path=/docs/components-actionmenu--docs
=> ActionMenu - Fix for documentation

packages/react-components/src/components/Card/Card.mdx
Card docs update.
https://feature-card-docs-update--613a8e945a5665003a05113b.chromatic.com/?path=/docs/components-card--docs
=> Card - Docs update

packages/react-components/src/components/Button/Button.mdx
Button docs update.
https://feature-button-docs-update--613a8e945a5665003a05113b.chromatic.com/?path=/docs/components-button--docs
=> Button - Docs update

packages/react-components/src/components/ActionMenu/ActionMenu.mdx, packages/react-components/src/components/Avatar/Avatar.mdx, packages/react-components/src/components/Badge/Badge.mdx, packages/react-components/src/components/Button/Button.mdx, packages/react-components/src/components/Card/Card.mdx, packages/react-components/src/components/Checkbox/Checkbox.mdx, packages/react-components/src/components/Checkbox/Checkbox.tsx, packages/react-components/src/components/DatePicker/DatePicker.mdx, packages/react-components/src/components/DatePicker/RangeDatePicker.mdx, packages/react-components/src/components/Form/Form.tsx, packages/react-components/src/components/FormGroup/FormGroup.tsx, packages/react-components/src/components/Icon/Icon.mdx, packages/react-components/src/components/Icon/Icon.tsx, packages/react-components/src/components/Input/Input.mdx, packages/react-components/src/components/Loader/Loader.mdx, packages/react-components/src/components/Modal/Modal.mdx, packages/react-components/src/components/Modal/Modal.tsx, packages/react-components/src/components/Modal/ModalBase.tsx
Improving storybook docs for following components:
- ActionMenu
- Avatar
- Badge
- Button
- Card
- Checkbox
- DatePicker
- Icon
- Input
- Loader
- Modal
https://feature-storybook-docs-pt1--613a8e945a5665003a05113b.chromatic.com
=> Improving storybook docs

README.md, packages/example-react/package-lock.json
=> Updating the README

README.md, docs/customized-components/Menu.js
Small changes in old docs after moving to `beta` with new DS.
=> Update old docs

packages/react-components/.storybook/preview.js, packages/react-components/src/foundations/radius-token.ts, packages/react-components/src/foundations/radius.css, packages/react-components/src/index.scss, packages/react-components/src/index.ts
Resolves: #680 
Added radius tokens to styles.
https://feature-680--613a8e945a5665003a05113b.chromatic.com/
=> #680 - Radius tokens

packages/react-components/src/components/Picker/Picker.tsx, packages/react-components/src/components/Picker/TriggerBody.spec.tsx, packages/react-components/src/components/Picker/TriggerBody.tsx
Resolves: #651 
https://feature-651--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-picker--default&args=type:multi;clearSearchAfterSelection:!true
=> #651 - Picker - Auto clear search option

packages/react-components/src/components/Toast/Toast.module.scss
Resolves: #670 
Correct spacing token for main container.
https://feature-670--613a8e945a5665003a05113b.chromatic.com/?path=/docs/components-toast--docs
=> #670 - Toast - Spacing change

packages/react-components/src/components/Modal/Modal.mdx, packages/react-components/src/components/Modal/Modal.module.scss, packages/react-components/src/components/Modal/Modal.spec.tsx, packages/react-components/src/components/Modal/Modal.stories.tsx, packages/react-components/src/components/Modal/Modal.tsx, packages/react-components/src/components/Modal/ModalBase.spec.tsx, packages/react-components/src/components/Modal/ModalBase.tsx, packages/react-components/src/components/Modal/ModalCloseButton.tsx, packages/react-components/src/components/Modal/ModalHeader.module.scss, packages/react-components/src/components/Modal/ModalHeader.tsx, packages/react-components/src/components/Modal/StoriesComponents.tsx, packages/react-components/src/foundations/spacing.css
Resolves: #687 
Changes related to refresh UI.
https://feature-687--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-modal--modal-with-custom-header
=> #687 - Modal - Refreshed UI

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature.md
Reverting Github issue templates
=> Reverting Github issue templates

packages/react-components/src/components/SegmentedControl/SegmentedControl.module.scss
Resolves: #688 
Changes related to refresh ui.
https://feature-688--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-segmented-control--default
=> #688 - Segmented Control - UI Refresh

packages/react-components/src/components/TagInput/TagInput.module.scss
Resolves: #689 
Changes related to refresh ui.
https://feature-689--613a8e945a5665003a05113b.chromatic.com/?path=/story/forms-tag-input--default-email-tag-input
=> #689 - Tag input - UI refresh for tag input

packages/react-components/src/components/Tab/Tab.module.scss
Resolves: #706 
https://feature-706--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-tabs--tabs-wrapper
=> #706 - Tab - UI changes for border

packages/react-components/src/components/ActionMenu/ActionMenu.module.scss, packages/react-components/src/components/ActionMenu/ActionMenu.tsx, packages/react-components/src/components/Alert/Alert.module.scss, packages/react-components/src/components/Alert/Alert.tsx, packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx, packages/react-components/src/components/Card/Card.tsx, packages/react-components/src/components/Input/Input.tsx, packages/react-components/src/components/Modal/Modal.module.scss, packages/react-components/src/components/Modal/Modal.stories.tsx, packages/react-components/src/components/Modal/ModalCloseButton.tsx, packages/react-components/src/components/PromoBanner/PromoBanner.tsx, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx, packages/react-components/src/components/Search/Search.module.scss, packages/react-components/src/components/Search/Search.tsx, packages/react-components/src/components/Toast/Toast.module.scss, packages/react-components/src/components/Toast/Toast.tsx, packages/react-components/src/components/Tooltip/Tooltip.module.scss, packages/react-components/src/components/Tooltip/components/Info.tsx, packages/react-components/src/components/Tooltip/components/Interactive.tsx, packages/react-components/src/components/Tooltip/components/UserGuide/UserGuideStep.tsx, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #723 
Package of changes to the `Button` component.
This PR covering the issues:
- #723 
- #722 
- #730 
- #724 
- #725 
- #731 
These PR bring the following breaking changes:
- new styles for `text` kind
- renaming `subtle` kind to `plain`
- renaming old `plain` and `plain-light` kinds to `link` and `link-light`
Also, in these changes we decided to change native `button` elements in other components to our `Button` component.
https://feature-723--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-button--kinds-and-states
=> #723 - Button - New High Contrast Button variant, styles updates

packages/react-components/src/components/Alert/Alert.tsx
Resolves: #726 
Changed button kinds.
https://feature-726--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-alert--with-cta
=> #726 - Alert - Change buttons kind

packages/react-components/src/components/Alert/Alert.tsx, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx, packages/react-components/src/components/Typography/Display.tsx, packages/react-components/src/components/Typography/Typography.module.scss, packages/react-components/src/components/Typography/index.ts, packages/react-components/src/stories/Typography.stories.mdx
Resolves: #727 
https://feature-727--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-promobannerv2--with-styled-additional-content
New typography tokens:
https://feature-727--613a8e945a5665003a05113b.chromatic.com/?path=/docs/foundations-typography--docs#display
=> #727 - PromoBannerV2 - Updates in documentation and new typography tokens

packages/react-components/src/components/Tag/Tag.module.scss, packages/react-components/src/components/Tag/Tag.stories.tsx, packages/react-components/src/components/Tag/Tag.tsx
Resolves: #748 
New component size.
https://feature-748--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-tag--sizes
=> #748 - Tag - New size + documentation update

packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx
Resolves: #749 
New variant.
https://feature-749--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-button--kinds-and-states
=> #749 - Button - New variant

packages/react-components/src/components/Picker/PickerList.tsx
Possible fix for 744
https://feature-possible-fix-for-744--613a8e945a5665003a05113b.chromatic.com
=> Possible fix for 744

lerna.json, package-lock.json, packages/react-components/package.json, packages/react-components/src/components/Icon/Icon.tsx, packages/react-components/src/components/Icon/index.ts, packages/react-components/src/components/Icon/types.ts, packages/react-components/src/components/Picker/types.ts, packages/react-components/src/components/UploadBar/UploadBar.stories.tsx
Fix for import issue in Icon component
=> Fix for import issue in Icon component

packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #782 
Updating surface avatar color tokens for all themes
https://feature-782--613a8e945a5665003a05113b.chromatic.com
=> [Color tokens] - Update avatars colors

packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #773 
New tokens for gradients.
https://feature-773--613a8e945a5665003a05113b.chromatic.com/?path=/docs/foundations-color-tokens--docs
=> #773 - New gradient tokens

packages/react-components/src/components/Badge/Badge.module.scss
Resolves: #808 
Change the `small` size width.
https://feature-808--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-badge--sizes
=> #808 - Badge - Changes to small size

package-lock.json, packages/react-components/package.json
Removing unused babel/core and babel-parser deps.
=> build(deps): removing unused babel dev deps

packages/react-components/src/components/Tooltip/Tooltip.tsx, packages/react-components/src/components/Tooltip/components/FloatingComponent.tsx
Little changes with `floating-ui` lib usage in the component.
https://feature-tooltip-positioning-bug--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-actionmenu--keep-open-on-item-click
=> fix(Tooltip): Fix for floating element wrong placement

packages/react-components/src/components/Avatar/Avatar.module.scss
Resolves: #856 
Disabling user-select on avatar component
https://feature-856--613a8e945a5665003a05113b.chromatic.com/{link-related-to-the-story}
=> fix(Avatar): Disable user select on avatar component

packages/react-components/src/components/Picker/PickerList.module.scss
Resolves: #852 
Remove blue notch from selected item in a picker list
https://feature-LC-793--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): Remove blue notch from selected item in a picker list

package-lock.json, packages/react-components/package.json, packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx, packages/react-components/src/components/Button/helpers.ts, packages/react-components/src/components/Button/index.ts, packages/react-components/src/components/Button/types.ts, packages/react-components/src/stories/components/StoryDescriptor.tsx
Resolves: #831 
Adding new link-inverted button kind
https://feature-831--613a8e945a5665003a05113b.chromatic.com
=> feat(Button): Add new link-inverted button kind

packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.tsx, packages/react-components/src/components/Button/styles/base.scss, packages/react-components/src/components/Button/styles/icon.scss, packages/react-components/src/components/Button/styles/kind.scss, packages/react-components/src/components/Button/styles/loader.scss, packages/react-components/src/components/Button/styles/size.scss
Resolves: #861 
Showing focus ring for Plain button only on :focus-state 
https://feature-861--613a8e945a5665003a05113b.chromatic.com
=> fix(Button): #861 - update active and focus states

packages/react-components/src/components/PromoBanner/PromoBanner.mdx, packages/react-components/src/components/PromoBanner/PromoBanner.tsx
Resolves: #747
Adding banner in component's story about deprecation.
I've also added a [new issue to remove PromoBanner](https://github.com/livechat/design-system/issues/872) in DS version 2.0.0
https://feature-747--613a8e945a5665003a05113b.chromatic.com
=> docs(PromoBanner): add information about component deprecation

packages/react-components/src/components/PromoBannerV2/PromoBannerV2.module.scss
Resolves: #877 
https://feature-877--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-promobannerv2--with-styled-additional-content
=> fix(PromoBannerV2): Style fixes

packages/react-components/src/components/Alert/Alert.module.scss, packages/react-components/src/components/Alert/Alert.tsx
Resolves: #878
https://feature-878--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-alert--with-cta
=> fix(Alert): Change in buttons align

packages/react-components/src/components/ActionBar/ActionBar.module.scss, packages/react-components/src/components/ActionBar/ActionBar.spec.tsx, packages/react-components/src/components/ActionBar/ActionBar.stories.tsx, packages/react-components/src/components/ActionBar/ActionBar.tsx, packages/react-components/src/components/ActionBar/ActionBarItem.tsx, packages/react-components/src/components/ActionBar/index.ts, packages/react-components/src/components/ActionBar/types.ts, packages/react-components/src/components/ActionMenu/ActionMenu.tsx, packages/react-components/src/components/Button/styles/icon.scss
Resolves: #882 
Vertical mode for component.
Improved selected item indicator, from now it indicates the element selected from the menu with icon visible.
Also changed the `ActionMenu` logic and added the animation on menu show.
https://feature-882--613a8e945a5665003a05113b.chromatic.com/?path=/docs/experimental-actionbar--docs
=> feat(ActionBar): vertical mode, selected item icon if not visible

packages/react-components/src/components/DetailsCard/DetailsCard.module.scss
https://feature-details-card-styles-fix--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-detailscard--example-usage
=> fix(DetailsCard): Styles fix

packages/react-components/.storybook/preview.js, packages/react-components/src/foundations/transition-token.ts, packages/react-components/src/foundations/transition.css, packages/react-components/src/index.scss, packages/react-components/src/index.ts, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/design-token.ts, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #907 
https://feature-907--613a8e945a5665003a05113b.chromatic.com/
=> feat(TransitionTokens): Transition types and duration tokens + new color token

packages/react-components/src/foundations/shadow-token.ts, packages/react-components/src/foundations/shadow.css
New token
https://feature-action-menu-textarea--613a8e945a5665003a05113b.chromatic.com/
=> feat(MessageBox token): New messagebox token

packages/react-components/src/components/DatePicker/DatePickerNavbar.tsx, packages/react-components/src/components/DatePicker/DatePickerRangeCalendarsWrapper.tsx, packages/react-components/src/components/DatePicker/helpers.ts, packages/react-components/src/foundations/radius-token.ts, packages/react-components/src/foundations/radius.css, packages/react-components/src/foundations/spacing-token.ts, packages/react-components/src/foundations/spacing.css
Changing clsx import to the dafault export.
=> fix(DatePicker): fix for clsx import

packages/react-components/src/components/DatePicker/index.ts
Add DatePickerRangeCalendarsWrapper to the DatePicker main export path.
=> fix(DatePicker): fixing DatePickerRangeCalendarsWrapper export path

packages/react-components/src/components/Tooltip/Tooltip.tsx, packages/react-components/src/components/Tooltip/types.ts
https://feature-tooltip-update--613a8e945a5665003a05113b.chromatic.com/?path=/docs/components-tooltip--docs
=> feat(Tooltip): useClick hook props for Tooltip component

packages/react-components/src/themes/light.scss
Resolves: #919 
Updating the color token SurfacePrimaryHover
https://feature-919--613a8e945a5665003a05113b.chromatic.com
=> fix(DesignToken): updating SurfacePrimaryHover value for light theme

packages/react-components/src/foundations/transition-token.ts, packages/react-components/src/foundations/transition.css, packages/react-components/src/index.ts, packages/react-components/src/stories/Radius.stories.mdx, packages/react-components/src/stories/Transition.stories.mdx, packages/react-components/src/stories/components/Table.css, packages/react-components/src/stories/components/Transition/TransitionTable.tsx, packages/react-components/src/stories/components/Transition/transitionDelay.ts, packages/react-components/src/stories/components/Transition/transitionDuration.ts, packages/react-components/src/stories/components/Transition/transitionTiming.ts
Resolves: #916
Adding new delay tokens and Transition story
https://feature-916--613a8e945a5665003a05113b.chromatic.com/?path=/docs/foundations-transition--docs
=> fix(TransitionToken): Adding new delay tokens and Transition story

.github/workflows/update-pr-description.yml, packages/react-components/src/components/Badge/Badge.module.scss
Resolves: #868
Changing tertiary color
https://feature-868--613a8e945a5665003a05113b.chromatic.com
=> fix(Badge): Changing tertiary color

packages/react-components/src/components/Alert/Alert.module.scss
Resolves: #949
https://feature-949--613a8e945a5665003a05113b.chromatic.com
=> fix(Alert): move margin to cta container for small and medium sizes

packages/icons/package.json, packages/icons/scripts/updateExports.js, packages/react-components/src/components/Picker/components/PickerListItem.module.scss
Fixing Picker styling issues
https://feature-picker-fixes--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): Minor fixes

packages/react-components/src/components/Button/styles/icon.scss
Resolves: #946
Fixes for styles for `icon-only` buttons.
https://feature-946--613a8e945a5665003a05113b.chromatic.com
=> fix(Button): Styles fixes

packages/react-components/src/components/Tooltip/Tooltip.module.scss
Fixing wrong styling for tooltip arrow in inverted mode.
https://feature-tooltip-arrow-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(Tooltip): tooltip arrow style fix

package-lock.json
=> build(deps-dev): updating get-func-name version

packages/react-components/src/components/PromoBanner/PromoBanner.tsx
A wrong reference was provided to remove event listener. It made all listeners to stay in memory along with their scopes.
=> fix(PromoBanner): Fix memory leak

lerna.json, package-lock.json, packages/example-react/package.json, packages/react-components/.storybook/main.js, packages/react-components/package.json, packages/react-components/src/components/Modal/components/ModalHeader.tsx, packages/react-components/src/foundations/index.ts, packages/react-components/src/index.ts, packages/react-components/vite.config.ts
https://feature-build-improvements--613a8e945a5665003a05113b.chromatic.com
=> fix(build): Reverting tree-shaking components due to css injection issues

packages/react-components/src/components/Card/Card.tsx, packages/react-components/src/components/Modal/Modal.tsx, packages/react-components/src/components/Modal/components/ModalHeader.module.scss, packages/react-components/src/components/Modal/components/ModalHeader.tsx, packages/react-components/src/components/Typography/Typography.module.scss
Resolves: #1006
- `display-max` styles update
- `paragraph-md` styles update
- `Card` and `Modal` components header changes
https://feature-1006--613a8e945a5665003a05113b.chromatic.com/?path=/docs/foundations-typography--docs
=> fix(Typography): tokens updates, modal and card components header changes

packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Use `root` in the light theme, as this is the default palette.
https://feature-css-light-theme-root--613a8e945a5665003a05113b.chromatic.com/?path=/docs/foundations-color--docs
=> fix(Color): use root with light theme as default theme

packages/react-components/src/components/Input/Input.module.scss, packages/react-components/src/components/Input/Input.tsx
Resolves: #1020
Bug fix - correct text color for disabled state if any value is given to the input
https://feature-1020--613a8e945a5665003a05113b.chromatic.com
=> fix(Input): change color for disabled state if value is given

packages/react-components/src/components/FormField/FormField.module.scss, packages/react-components/src/components/FormField/FormField.stories.tsx, packages/react-components/src/components/FormField/FormField.tsx
Resolves: #1023
Typography fix for label.
Prevented to use some of props in SB controls.
https://feature-1023--613a8e945a5665003a05113b.chromatic.com
=> fix(FormField): Docs controls changes, style changes

.husky/pre-commit, .lintstagedrc, .lintstagedrc.json, packages/react-components/package.json, packages/react-components/scripts/generateDesignTokenEnum.js, packages/react-components/src/foundations/design-token.ts, packages/react-components/src/stories/foundations/Color/Color.stories.mdx, packages/react-components/src/stories/foundations/Color/data.ts, packages/react-components/src/stories/foundations/Color/types.ts, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #1030
- Adding new DesignTokens
- Adding type-checking on pre-commit hook with husky 
- Adding color enums generation with lint-staged
https://feature-1030--613a8e945a5665003a05113b.chromatic.com
=> fix(DesignToken): Adding new tokens; generating token enums with lint-staged

packages/react-components/src/components/Button/styles/base.scss, packages/react-components/src/components/Button/styles/kind.scss
Resolves: #1022
Fix for the issue where focus state designed to keyboard control is visible after mouse click.
https://feature-1022--613a8e945a5665003a05113b.chromatic.com
=> fix(Button): Fix the focus state for keyboard control

packages/icons/tsconfig.json
=> build(Icons): reverting TS target

packages/icons/package.json
Fixing Node exports for icons components in package.json
=> build(Icons): fixing exports for icons

packages/react-components/src/components/Modal/Modal.module.scss, packages/react-components/src/components/Modal/Modal.stories.tsx
Simple animation for modal.
https://feature-modal-animation--613a8e945a5665003a05113b.chromatic.com
=> fix(Modal): added animation on modal show, stories update

packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/Picker/components/PickerListItem.tsx
Resolves: #1054
After implementing typography tokens, we missed that picker list items which displays avatar, checkbox, etc are broken.
This fix resolves that.
We also added `openOnInit` flag to components in some stories to be able to monitor the correct design through chromatic.
https://feature-1054--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): list item bug fix

packages/react-components/src/components/Picker/Picker.tsx, packages/react-components/src/components/Picker/components/PickerList.tsx, packages/react-components/src/components/Picker/hooks/useFloatingPicker.ts, packages/react-components/src/components/Picker/types.ts
Resolves: #1053
Adding the `maxListHeight` to Picker component to control list height.
https://feature-1053--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): adding maxListHeight prop

packages/react-components/src/components/Avatar/Avatar.module.scss, packages/react-components/src/components/Avatar/Avatar.stories.tsx, packages/react-components/src/components/Avatar/Avatar.tsx, packages/react-components/src/components/Avatar/styles/size.scss, packages/react-components/src/components/Avatar/types.ts, packages/react-components/src/stories/components/StoryDescriptor.tsx
Resolves: #1058
- Adding minHeight and minWidth for avatar sizes to prevent shrinking
- Refactoring styles using mixins
https://feature-1058--613a8e945a5665003a05113b.chromatic.com
=> fix(Avatar): minHeight and minWidth for avatar

packages/react-components/src/components/Input/Input.module.scss, packages/react-components/src/components/Input/Input.tsx
Resolves: #1059
Programmatically focus internal input component on wrapper click 
https://feature-1059--613a8e945a5665003a05113b.chromatic.com
=> fix(Input): fixing missing input focus on wrapper click

packages/react-components/src/components/Picker/helpers.ts, packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Resolves: #1064
Fixing controlled mode for selected items
https://feature-1064--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): fixing controlled mode for selected items

packages/react-components/src/themes/dark.scss
Resolves: #1084
Updating color token
https://feature-1084--613a8e945a5665003a05113b.chromatic.com
=> fix(DesignToken): updating color token

packages/react-components/src/components/Tooltip/Tooltip.module.scss, packages/react-components/src/components/Tooltip/components/UserGuide/UserGuide.tsx
=> fix(UserGuide): fixing the nullish parent element issue

packages/react-components/src/components/Tooltip/Tooltip.module.scss, packages/react-components/src/foundations/design-token.ts, packages/react-components/src/foundations/shadow-token.ts, packages/react-components/src/foundations/shadow.css, packages/react-components/src/stories/foundations/Color/data.ts, packages/react-components/src/stories/foundations/Shadow/constants.ts, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #1069 
Tokens values update, new tokens, UI of tooltips update.
https://feature-1069--613a8e945a5665003a05113b.chromatic.com
=> fix(Tokens): tokens update, tooltip ui update

packages/react-components/src/components/Picker/components/PickerListItem.module.scss, packages/react-components/src/components/Picker/components/PickerListItem.tsx, packages/react-components/src/components/Picker/components/PickerTrigger.tsx
Resolves: #1088
https://feature-1088--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): ellipsis for list items and selected item

packages/react-components/src/components/Checkbox/Checkbox.module.scss, packages/react-components/src/components/Checkbox/Checkbox.stories.tsx
Resolves: #1079
https://feature-1079--613a8e945a5665003a05113b.chromatic.com
=> fix(Checkbox): UI fixes (checked disabled state, hover and focus states)

packages/react-components/src/components/Switch/Switch.module.scss, packages/react-components/src/components/Switch/Switch.tsx
Resolves: #1080 
Focus state + UI update for disabled state.
https://feature-1080--613a8e945a5665003a05113b.chromatic.com
=> fix(Switch): ui updates

packages/react-components/src/components/PromoBannerV2/PromoBannerV2.stories.tsx, packages/react-components/src/components/Typography/Display.tsx, packages/react-components/src/components/Typography/Typography.module.scss, packages/react-components/src/components/Typography/types.ts, packages/react-components/src/stories/foundations/Typography/components/DisplayExamples.tsx
Resolves: #1083
New `Display` size, bold type style updates.
https://feature-1083--613a8e945a5665003a05113b.chromatic.com
=> fix(Typography): ui updates + new display variant

packages/react-components/src/components/Button/Button.tsx, packages/react-components/src/components/Button/styles/icon.scss
Resolves: #1044
Change icon size for `xcompact` button size.
https://feature-1044--613a8e945a5665003a05113b.chromatic.com
=> fix(Button): change icon size for xcompact button

packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
Resolves: #1032
UI fix for border radius
https://feature-1032--613a8e945a5665003a05113b.chromatic.com
=> fix(ActionMenu): ui fix with border radius

packages/react-components/src/components/Picker/components/PickerTrigger.module.scss
Resolves: #1101
Change token for border color disabled state.
https://feature-1101--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): ui fix for border disabled state

packages/react-components/src/components/ActionMenu/ActionMenu.module.scss
Resolves: #1095
https://feature-1095--613a8e945a5665003a05113b.chromatic.com
=> fix(ActionMenu): use opacity for disabled elements

packages/react-components/src/components/DatePicker/RangeDatePicker.mdx
Resolves: #1092 
The report shows that there is a problem with the component, but it seems to be an incorrect implementation of this component. From what I noticed, it may be related to an incorrect code snippet in the documentation that does not take into account the full implementation.
https://feature-1092--613a8e945a5665003a05113b.chromatic.com
=> fix(RangeDatePicker): correct code snippet in docs

packages/react-components/src/foundations/design-token.ts, packages/react-components/src/stories/foundations/Color/data.ts, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #1122
Adding and updating color tokens
https://feature-1122--613a8e945a5665003a05113b.chromatic.com
=> fix(ColorTokens): new and updated color tokens

docs/TESTING.md
=> docs(TESTING): docs update

packages/react-components/src/components/Badge/Badge.spec.tsx, packages/react-components/src/components/Badge/Badge.tsx
=> fix(Badge): tests updates

packages/react-components/src/foundations/design-token.ts, packages/react-components/src/stories/foundations/Color/data.ts, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #1166
Adding new DS tokens
https://feature-1166--613a8e945a5665003a05113b.chromatic.com
=> fix(DesignToken): adding new One gradients

packages/react-components/src/components/FieldGroup/FieldGroup.spec.tsx
=> fix(FieldGroup): tests updates

packages/react-components/src/components/PromoBannerV2/PromoBannerV2.spec.tsx, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
=> fix(PromoBanner): tests updates

packages/react-components/src/components/Tab/Tab.spec.tsx, packages/react-components/src/components/Tab/Tab.tsx, packages/react-components/src/components/Tab/TabsWrapper.spec.tsx, packages/react-components/src/components/Tab/TabsWrapper.tsx
=> fix(Tab): tests updates

packages/react-components/src/components/TagInput/TagInput.spec.tsx
=> fix(TagInput): tests updates

packages/react-components/src/components/NumericInput/NumericInput.spec.tsx
=> fix(NumericInput): tests updates

packages/react-components/src/components/FileUploadProgress/FileUploadProgress.spec.tsx, packages/react-components/src/components/FileUploadProgress/FileUploadProgress.tsx
=> fix(FileUploadProgress): tests updates

packages/react-components/src/components/DatePicker/DatePicker.spec.tsx, packages/react-components/src/components/DatePicker/RangeDatePicker.spec.tsx
=> fix(DatePicker): tests updates

packages/react-components/src/components/Picker/Picker.spec.tsx, packages/react-components/src/components/Picker/components/PickerList.tsx, packages/react-components/src/components/Picker/components/PickerTrigger.spec.tsx, packages/react-components/src/components/Picker/components/PickerTrigger.tsx, packages/react-components/src/components/Picker/components/PickerTriggerBody.spec.tsx
=> fix(Picker): tests updates

packages/react-components/src/components/Typography/Typography.module.scss, packages/react-components/src/components/Typography/types.ts, packages/react-components/src/stories/foundations/Typography/components/TextExamples.tsx
Resolves: #1142
Update for `font-weight` for `heading-md`.
New `paragraph-lg` size.
https://feature-1142--613a8e945a5665003a05113b.chromatic.com
=> fix(Typography): styles update and new paragraph size

packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #1220
Token color update/
https://feature-1220--613a8e945a5665003a05113b.chromatic.com
=> fix(Color): token color update

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/update-pr-description.yml
Adding the automatic branch name insertion to get rid of redundant work.
=> build(GithubActions): automatically insert branch name

packages/react-components/src/components/Picker/components/PickerListItem.module.scss, packages/react-components/src/components/Picker/components/PickerListItem.tsx
Disabling overflow for custom content to prevent custom row from uncontrolled growing
https://feature-1241--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): fixing overflow on selected custom elements

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
Adding codeowners file
https://feature-adding-codeowners--613a8e945a5665003a05113b.chromatic.com
=> chore(Github): adding codeowners file

packages/react-components/src/components/Picker/Picker.tsx
Resolves: [Slack thread](https://text.slack.com/archives/CCRBKU2AD/p1721305366433939)
Set clearSearchAfterSelection as true by default
https://feature-picker-clean-by-default--613a8e945a5665003a05113b.chromatic.com
=> feat(Picker): set clearSearchAfterSelection as true by default

packages/icons/svg/arrows-sort.svg, packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Resolves: [#1265](https://github.com/livechat/design-system/issues/1265)
https://feature-1265--613a8e945a5665003a05113b.chromatic.com
=> feat(Icon): adding arrows-sort icon

packages/react-components/src/components/AppFrame/AppFrame.module.scss, packages/react-components/src/components/AppFrame/AppFrame.stories.css, packages/react-components/src/components/AppFrame/AppFrame.stories.tsx, packages/react-components/src/components/AppFrame/components/NavigationGroup/NavigationGroup.module.scss, packages/react-components/src/components/AppFrame/components/SideNavigation/SideNavigation.module.scss, packages/react-components/src/components/AppFrame/stories-helpers.tsx
Fixed the issue with scroll in Safari browser.
Changed the styles of the top bar.
https://feature-1268--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-appframe--default
=> fix(AppFrame): main nav scrollbar fix for safari

packages/react-components/src/components/Modal/index.ts
Adding missing export for ActionModalContent component
https://feature-modal-export-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(Modal): adding export for ActionModalContent

packages/react-components/src/components/Picker/components/PickerList.module.scss, packages/react-components/src/components/Picker/components/PickerList.tsx
Resolves: #1257
Adding styles to no results text
https://feature-1257--613a8e945a5665003a05113b.chromatic.com
=> fix(PickerList): styles for no results

packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
Fix for correct setting content size.
https://feature-onboarding-checklist-resize-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(OnboardingChecklist): resize observer fix

packages/react-components/src/components/ProductSwitcher/constants.ts
Fixing product names
https://feature-switcher-typo-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): fix typo

packages/react-components/src/foundations/design-token.ts, packages/react-components/src/stories/foundations/Color/data.ts, packages/react-components/src/themes/dark.scss, packages/react-components/src/themes/legacy.scss, packages/react-components/src/themes/light.scss
Resolves: #1249
Adding new color token
https://feature-1249--613a8e945a5665003a05113b.chromatic.com
=> fix(Colors): adding new color token

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/types.ts
Adding optional onSelect handler
https://feature-switcher-onselect-handler--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): optional onselect handler

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.module.scss, packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx, packages/react-components/src/components/ProductSwitcher/helpers.spec.ts, packages/react-components/src/components/ProductSwitcher/helpers.ts, packages/react-components/src/utils/plural.ts
- Closing switcher list when clicking "powered by text"
- Calculating trial days left as difference in calendar days
https://feature-switcher-tweaks--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): minor improvements

packages/react-components/.storybook/main.ts, packages/react-components/src/components/AppFrame/AppFrame.stories.tsx, packages/react-components/src/components/AppFrame/AppFrame.tsx, packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.module.scss, packages/react-components/src/components/AppFrame/components/NavigationItem/NavigationItem.tsx, packages/react-components/src/components/AppFrame/components/NavigationItem/types.ts, packages/react-components/src/components/AppFrame/stories-helpers.tsx
- Adding `disabled` state to NavigationItem
- Making `url` and `label` fields optional
- Removing `disableTooltip` prop as it will no longer be needed after making `label` field optional
https://feature-appframe-fixes--613a8e945a5665003a05113b.chromatic.com
- [ x Self review (use this as your final check for proposed changes before requesting the review)
=> fix(AppFrame): Fixes and Improvements

packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.stories.tsx, packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.tsx, packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss, packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx, packages/react-components/src/components/OnboardingChecklist/types.ts, packages/react-components/vite.config.ts
- Adding titleHint prop to the OnboardingChecklist
- Fixing providers export
https://feature-onboarding-checklist-fixes--613a8e945a5665003a05113b.chromatic.com
=> fix(OnboardingChecklist): adding title hint prop

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
https://feature-switcher-fixes--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): reverting redirect and invert kind for tooltip

packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.module.scss, packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.stories.tsx, packages/react-components/src/components/OnboardingChecklist/OnboardingChecklist.tsx, packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss, packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
https://feature-checklist-fixes--613a8e945a5665003a05113b.chromatic.com
=> fix(OnboardingChecklist): fixes and improvements

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx, packages/react-components/src/components/ProductSwitcher/helpers.ts
Focusing existing tab or open new.
https://feature-switcher-tap-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): open or focus existing tab

packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.module.scss, packages/react-components/src/components/OnboardingChecklist/components/CheckListItem.tsx
Check commit messages
https://feature-checklist-fixes--613a8e945a5665003a05113b.chromatic.com
=> fix(OnboardingChecklist): minor fixes

packages/react-components/src/components/AppFrame/AppFrame.stories.tsx, packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx, packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx, packages/react-components/src/components/ProductSwitcher/constants.ts, packages/react-components/src/components/ProductSwitcher/helpers.spec.ts, packages/react-components/src/components/ProductSwitcher/helpers.ts, packages/react-components/src/components/ProductSwitcher/hooks/useProductSwitcher.ts, packages/react-components/src/components/ProductSwitcher/types.ts
Resolves: [slack thread](https://text.slack.com/archives/C07CCL0CAPP/p1724150528269429)
Add UTMs to product redirects
https://613a8e945a5665003a05113b-sjblzvnzew.chromatic.com/
=> feat(product-switcher): Add UTMs to product redirects; revert open or focus existing tab 

packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.tsx
Resolves: N/A
Allow to focus switcher with tab keys
https://feature-allow-focus-switcher-with-tab-key--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): Allow to focus switcher with tab keys

packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx
Copy change for trial expiring tooltip.
https://feature-product-switcher-copy-change--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): trail expiring copy change

packages/react-components/src/components/AppFrame/AppFrame.mdx, packages/react-components/src/components/AppFrame/AppFrame.stories.tsx, packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.module.scss, packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.spec.tsx, packages/react-components/src/components/AppFrame/components/ExpirationCounter/ExpirationCounter.tsx, packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx, packages/react-components/src/components/AppFrame/components/index.ts
Added `ExpirationCounter` component.
Changed button kind for top bar alert.
Updated documentation.
https://feature-app-frame-counter-component--613a8e945a5665003a05113b.chromatic.com
=> feat(AppFrame): expiration counter component and fixes

packages/react-components/src/components/Tooltip/Tooltip.tsx
Resolves: #1311 
Added padding parameter for tooltip arrow, to prevent overflow rounded corners.
https://feature-1311--613a8e945a5665003a05113b.chromatic.com
=> fix(Tooltip): Arrow position fix

packages/react-components/src/components/Link/Link.tsx
Resolves: #1046
Marking bold prop as optional
https://feature-1046--613a8e945a5665003a05113b.chromatic.com
=> fix(Link): marking bold prop as optional

packages/icons/svg/language.svg, packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Adds a Language icon
https://feature-language-icon--613a8e945a5665003a05113b.chromatic.com
=> feat(Icon): add Language icon

packages/react-components/src/components/Accordion/Accordion.tsx
https://feature-release-feat-test--613a8e945a5665003a05113b.chromatic.com
=> feat(Accordion): release test

packages/react-components/src/components/Accordion/Accordion.tsx
https://feature-{branch-name}--613a8e945a5665003a05113b.chromatic.com
=> feat(Accordion): release test v2

.github/workflows/check-pr-title.yml, .github/workflows/release.yml, .github/workflows/update-pr-description.yml, package-lock.json, packages/react-components/package.json, packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx, packages/react-components/src/components/ProductSwitcher/constants.ts, packages/react-components/src/components/ProductSwitcher/types.ts
=> chore(release): new release

.github/workflows/release.yml, package.json
https://feature-release-workflow-update--613a8e945a5665003a05113b.chromatic.com
=> fix(Release): workflow update

.github/workflows/release.yml, package.json
https://feature-{branch-name}--613a8e945a5665003a05113b.chromatic.com
=> fix(Release): workflow update (#1337)

package-lock.json
=> New release

packages/react-components/src/components/Button/Button.helpers.ts, packages/react-components/src/components/Button/Button.module.scss, packages/react-components/src/components/Button/Button.stories.tsx, packages/react-components/src/components/Button/Button.tsx, packages/react-components/src/components/Button/styles/animated-label.scss
A new `animatedLabel` prop will enable showing the button label on hover/focus.
https://feature-button-animation--613a8e945a5665003a05113b.chromatic.com/?path=/story/components-button--button-with-animated-label
=> feat(Button): animated label

packages/react-components/src/components/Button/Button.tsx, packages/react-components/src/components/Button/styles/animated-label.scss, packages/react-components/src/components/InviteAgents/InviteAgents.module.scss, packages/react-components/src/components/InviteAgents/InviteAgents.spec.tsx, packages/react-components/src/components/InviteAgents/InviteAgents.tsx, packages/react-components/src/components/InviteAgents/components/AnimatedButton/AnimatedButton.module.scss, packages/react-components/src/components/InviteAgents/components/AnimatedButton/AnimatedButton.tsx
Fixing menu and animated button label
https://feature-invite-agents-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(InviteAgents): fixing menu and animated button

packages/react-components/src/components/InviteAgents/InviteAgents.spec.tsx, packages/react-components/src/components/InviteAgents/InviteAgents.stories.tsx, packages/react-components/src/components/InviteAgents/InviteAgents.tsx, packages/react-components/src/components/InviteAgents/types.ts
Adding callback prop for clicking on the avatars
https://feature-invite-agents-avatar-click--613a8e945a5665003a05113b.chromatic.com
=> fix(InviteAgents): handle avatars click

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/types.ts
Add prop to change the theme mode. TeamChat doesnt have the app frame yet, so the light mode will work.
https://feature-product-switcher-theme-prop--613a8e945a5665003a05113b.chromatic.com
=> feat(ProductSwitcher): Add prop to change the theme mode

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.tsx, packages/react-components/src/components/ProductSwitcher/components/ProductRow/ProductRow.tsx, packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.module.scss, packages/react-components/src/components/ProductSwitcher/components/ProductTile/ProductTile.tsx, packages/react-components/src/components/ProductSwitcher/constants.ts, packages/react-components/src/components/ProductSwitcher/types.ts
Fix light mode case by using color tokens instead of hardcoded values
https://feature-fix-product-switcher-light-mode-colors--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): Use color tokens

packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx, packages/react-components/src/components/ProductSwitcher/constants.ts, packages/react-components/src/components/ProductSwitcher/types.ts
Rename Hello to TeamChat
https://feature-rename-hello-to-teamchat--613a8e945a5665003a05113b.chromatic.com
=> feat(ProductSwitcher): Rename hello to teamchat

.github/workflows/check-pr-title.yml
https://feature-pr-title-gh-action--613a8e945a5665003a05113b.chromatic.com
=> build(GithubAction): modifying check pr title action

packages/react-components/src/components/InviteAgents/InviteAgents.tsx, packages/react-components/src/components/InviteAgents/types.ts
Hiding bots info in tooltip option
https://feature-invite-agents-tweak--613a8e945a5665003a05113b.chromatic.com
=> fix(InviteAgents): hiding bots info in tooltip option

packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/Picker/hooks/usePickerItems.ts
Allowing removing selected items independently
https://feature-picker-remove-item-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(Picker): allow removing selected items independently

packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/Picker/components/PickerTriggerBody.tsx, packages/react-components/src/components/Picker/constants.tsx, packages/react-components/src/components/Picker/types.ts
allowing to pass custom tag options to selected items
https://feature-picker-custom-color-tag--613a8e945a5665003a05113b.chromatic.com
=> tweak(Picker): allowing to pass custom tag options to selected items

packages/react-components/.storybook/preview.js, packages/react-components/src/components/FormField/FormField.mdx, packages/react-components/src/components/FormField/FormField.stories.tsx, packages/react-components/src/components/Input/Input.mdx, packages/react-components/src/components/Input/Input.stories.tsx
Resolves: #1348
Better docs for Input and FormField components.
https://feature-1348--613a8e945a5665003a05113b.chromatic.com
=> docs(Input, FormField): better docs for Input and FormField components

.eslintignore, packages/react-components/src/components/PromoBanner/PromoBanner.mdx, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.mdx
Resolves: #1366 
Updating docs
https://feature-1366--613a8e945a5665003a05113b.chromatic.com
=> docs(PromoBannerV2): fix docs

package-lock.json, packages/react-components/tsconfig.json
https://feature-deps-update--613a8e945a5665003a05113b.chromatic.com
=> build(package): updating dependencies

packages/metrics/package.json
Moving scanner to project dependencies
https://feature-metrics-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(metrics): moving scanner to dependencies

packages/react-components/src/components/ProductSwitcher/constants.ts
Update client id after accounts release.
https://feature-fix-redirect-uri-tc--613a8e945a5665003a05113b.chromatic.com
=> fix(ProductSwitcher): TeamChat url and client fix

packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.module.scss, packages/react-components/src/components/AppFrame/components/NavigationTopBar/types.ts
Fixes.
https://feature-app-frame-top-bar-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(AppFrame): top bar styles update and interfaces fix

package-lock.json, packages/react-components/package.json, packages/react-components/src/components/AppFrame/AppFrame.stories.css, packages/react-components/src/components/AppFrame/stories-helpers.tsx, packages/react-components/src/components/Tooltip/Tooltip.tsx, packages/react-components/src/components/Tooltip/types.ts, packages/react-components/src/test/setup.ts
Resolves: https://text.slack.com/archives/CA945NPQR/p1728387697093949
Hiding the tooltip when its reference is hidden.
https://feature-tooltip-visibility-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(Tooltip): hide when reference is hidden

packages/react-components/src/components/Alert/Alert.tsx, packages/react-components/src/components/Picker/Picker.stories.tsx, packages/react-components/src/components/ProductSwitcher/ProductSwitcher.stories.tsx, packages/react-components/src/components/PromoBannerV2/PromoBannerV2.tsx
Resolves: #873 
Extending button props
https://feature-873--613a8e945a5665003a05113b.chromatic.com
=> tweak(Alert, InteractiveTooltip, PromoBannerV2): extending button props

packages/react-components/src/components/AppFrame/AppFrame.module.scss, packages/react-components/src/components/AppFrame/AppFrame.tsx, packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.spec.tsx, packages/react-components/src/components/AppFrame/components/NavigationTopBar/NavigationTopBar.tsx
Mobile alert will not overflow the content.
Reoved forced dark mode from the top bar.
https://feature-app-frame-mobile-top-bar-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(AppFrame): mobile alerts fix and top bar fix

packages/react-components/src/hooks/useAnimations.ts
Fix for the `useAnimations` hook.
https://feature-useAnimation-hook-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(useAnimations): hook fix

packages/react-components/src/hooks/useAnimations.ts
https://feature-useAnimations-hook-fix--613a8e945a5665003a05113b.chromatic.com
=> fix(useAnimations): fix for animations hook

packages/react-components/src/components/ProductSwitcher/constants.ts
Revert TeamChat is ready to be shown as a default product now.
https://feature-revert-default-teamchat--613a8e945a5665003a05113b.chromatic.com
=> feat(ProductSwitcher): Revert TeamChat as default product

packages/icons/svg/arrows_diagonal.svg, packages/icons/svg/arrows_diagonal_minimize.svg, packages/react-components/src/components/Icon/IconsShowcase/constans.ts
Relates to HD-4573
Adds two icons
https://feature-HD-4573-arrow-icons--613a8e945a5665003a05113b.chromatic.com
=> feat(Icon): add minimize-maximize icons

docs/customized-components/Menu.js
Resolves: n/a
Updates to modal message:
* Changed the modal heading from "Warning!" to "Legacy Version" and updated the modal content to inform users that the current Design System version is outdated and to use the updated resources at `design.livechat.com`.
n/a
=> fix(LegacyModal): fix legacy modal message
